StartAir_Safe: SimExManager Class Reference
SimExManager Class Reference
#include <SimExManager.h>
Classes
struct record_struct
Public Member Functions
SimExManager ()
~SimExManager ()
Protected Member Functions
void addSendRecord (HANDLE hSimConnect, char *c)
char * findSendRecord (DWORD id)
void firstSendRecord (HANDLE h, char *rn)
void lastSendRecord (HANDLE h)
Private Member Functions
void add (int id, char *c)
Private Attributes
int record_count = 0
struct record_struct send_record [max_send_records]
int firstSet
char * recordname
Detailed Description
Definition at line 7 of file SimExManager.h.
Constructor & Destructor Documentation
SimExManager::SimExManager ()
Definition at line 4 of file SimExManager.cpp.
References firstSet.
 {
         firstSet = -1;
 }
SimExManager::~SimExManager ()
Definition at line 10 of file SimExManager.cpp.
 {
 }
Member Function Documentation
void SimExManager::add (int id, char * c) private
Definition at line 42 of file SimExManager.cpp.
References record_count, send_record, and SimExManager::record_struct::sendid.
Referenced by addSendRecord(), and lastSendRecord().
 {
         strncpy_s(send_record[record_count].call, 255, c, 255);
         send_record[record_count].sendid = id;
         ++record_count;
 }
void SimExManager::addSendRecord (HANDLE hSimConnect, char * c) protected
Definition at line 29 of file SimExManager.cpp.
References add(), max_send_records, and record_count.
 {
         DWORD id;
         if (record_count < max_send_records)
         {
                 int hr = SimConnect_GetLastSentPacketID(hSimConnect, &id);
                 add(id,c);
         }
 }
char * SimExManager::findSendRecord (DWORD id) protected
Definition at line 16 of file SimExManager.cpp.
References SimExManager::record_struct::call, record_count, and send_record.
Referenced by safe::DataSender::onRecvException(), and safe::SimReceiver::onRecvException().
 {
         bool found = false;
         int count = 0;
         while (!found && count < record_count)
         {
                 if (id == send_record[count].sendid)
                         return send_record[count].call;
                 ++count;
         }
         return "Send Record not found";
 }
void SimExManager::firstSendRecord (HANDLE h, char * rn) protected
Definition at line 49 of file SimExManager.cpp.
References firstSet, and recordname.
Referenced by safe::DataSender::freeze().
{
         DWORD id;
         if (firstSet != -1 )
         {
                 std::cout << std::endl << "SimExManager, illegal firstSendRecord";
         }
         else
         {
                 recordname = rn;
                 int hr = SimConnect_GetLastSentPacketID(h, &id);
                 firstSet = id;
         }
 }
void SimExManager::lastSendRecord (HANDLE h) protected
Definition at line 63 of file SimExManager.cpp.
References add(), firstSet, and recordname.
Referenced by safe::DataSender::freeze().
{
         DWORD id;
         if (firstSet == -1)
         {
                 std::cout << std::endl << "SimExManager, illegal lastSendRecord";
         }
         else
         {
                 SimConnect_GetLastSentPacketID(h, &id);
                 int lastset = id;
                 for (int i = firstSet; i <= lastset; i++)
                 {
                         add(i, recordname);
                 }
                 firstSet = -1;
         }
 }
Member Data Documentation
int SimExManager::firstSet private
Definition at line 23 of file SimExManager.h.
Referenced by firstSendRecord(), lastSendRecord(), and SimExManager().
int SimExManager::record_count = 0 private
Definition at line 21 of file SimExManager.h.
Referenced by add(), addSendRecord(), and findSendRecord().
char* SimExManager::recordname private
Definition at line 24 of file SimExManager.h.
Referenced by firstSendRecord(), and lastSendRecord().
struct record_struct SimExManager::send_record[max_send_records] private
Definition at line 22 of file SimExManager.h.
Referenced by add(), and findSendRecord().
The documentation for this class was generated from the following files:
global/SimExManager.h
global/SimExManager.cpp