StartAir_Safe: safe::CSafeSS Class Reference
safe::CSafeSS Class Reference
#include <CSafeServerSide.h>
Public Member Functions
CSafeSS ()
~CSafeSS ()
void launch (int port)
Public Member Functions inherited from safe::ISimListener
virtual ~ISimListener ()
Protected Member Functions
void dataReceived (SimDataEvent &e)
void simQuitted (HANDLE h)
void simStopped (HANDLE h)
void simStarted (HANDLE h)
void latlonaltReceived (HANDLE h, SIMCONNECT_DATA_LATLONALT &d)
void PBHReceived (HANDLE h, SIMCONNECT_DATA_PBH &d)
void latLonAltPBHReceived (HANDLE h, SAFE_DATA_POS &d)
Private Attributes
UDPSender udps
Detailed Description
Definition at line 10 of file CSafeServerSide.h.
Constructor & Destructor Documentation
safe::CSafeSS::CSafeSS ()
Definition at line 11 of file CSafeServerSide.cpp.
                          : udps()
         {
         }
safe::CSafeSS::~CSafeSS ()
Definition at line 16 of file CSafeServerSide.cpp.
         {
         }
Member Function Documentation
void safe::CSafeSS::dataReceived (SimDataEvent & e) protected virtual
Implements safe::ISimListener.
Definition at line 49 of file CSafeServerSide.cpp.
         {
         }
void safe::CSafeSS::latLonAltPBHReceived (HANDLE h, SAFE_DATA_POS & d) protected virtual
Implements safe::ISimListener.
Definition at line 66 of file CSafeServerSide.cpp.
References SAFE_DATA_POS::Altitude, SAFE_DATA_POS::b, SAFE_DATA_POS::h, SAFE_DATA_POS::Latitude, SAFE_DATA_POS::Longitude, SAFE_DATA_POS::p, UDPSender::send(), and udps.
         {
                 cout << endl << "PLANE LATITUDE = " << d.Latitude;
                 cout << endl << "PLANE LONGITUDE = " << d.Longitude;
                 cout << endl << "PLANE ALTITUDE = " << d.Altitude;
                 cout << endl << "P = " << d.p;
                 cout << endl << "B = " << d.b;
                 cout << endl << "H = " << d.h;
                 udps.send((char*)&d, sizeof(d));
         }
void safe::CSafeSS::latlonaltReceived (HANDLE h, SIMCONNECT_DATA_LATLONALT & d) protected virtual
Implements safe::ISimListener.
Definition at line 53 of file CSafeServerSide.cpp.
{
                 cout << endl << "PLANE LATITUDE = " << d.Latitude;
                 cout << endl << "PLANE LONGITUDE = " << d.Longitude;
                 cout << endl << "PLANE ALTITUDE = " << d.Altitude;
                 //udps.send((char*)&d, sizeof(d));
         }
void safe::CSafeSS::launch (int port)
Definition at line 20 of file CSafeServerSide.cpp.
References safe::SimReceiver::addListener(), UDPSender::addTarget(), SimConnection::dispatch(), safe::SimReceiver::requestPos(), safe::SimReceiver::stop(), and udps.
Referenced by _tmain().
         {
                 udps.addTarget("127.0.0.1", port);
                 udps.addTarget("192.168.0.12", port);
                 SimReceiver sr = SimReceiver(0);
                 sr.requestPos();
                 //sr.requestLatLonAlt();
                 //sr.requestPBH();
                 sr.addListener(this);
                 while (!sr.stop())
                 {
                         //clock_t tbegin, tend;
                         //tbegin = clock();
                         sr.dispatch();
                         //ds.dispatch();
                         //tend = clock();
                         //      if (tend-tbegin !=0) cout << endl << "Temp dispatch :" << (tend - tbegin) << "-------------------------------------- "/*/ CLOCKS_PER_SEC * 1000*/;
                         Sleep(1);
                 }
         }
void safe::CSafeSS::PBHReceived (HANDLE h, SIMCONNECT_DATA_PBH & d) protected virtual
Implements safe::ISimListener.
Definition at line 59 of file CSafeServerSide.cpp.
References SIMCONNECT_DATA_PBH::b, SIMCONNECT_DATA_PBH::h, and SIMCONNECT_DATA_PBH::p.
{
                 cout << endl << "P = " << d.p;
                 cout << endl << "B = " << d.b;
                 cout << endl << "H = " << d.h;
                 //udps.send((char*)&d, sizeof(d));
         }
void safe::CSafeSS::simQuitted (HANDLE h) protected virtual
Implements safe::ISimListener.
Definition at line 45 of file CSafeServerSide.cpp.
 { cout << "\nSIM QUIT" << endl; }
void safe::CSafeSS::simStarted (HANDLE h) protected virtual
Implements safe::ISimListener.
Definition at line 47 of file CSafeServerSide.cpp.
 { cout << "\nSIM START" << endl; }
void safe::CSafeSS::simStopped (HANDLE h) protected virtual
Implements safe::ISimListener.
Definition at line 46 of file CSafeServerSide.cpp.
 { cout << "\nSIM STOP" << endl; }
Member Data Documentation
UDPSender safe::CSafeSS::udps private
Definition at line 25 of file CSafeServerSide.h.
Referenced by latLonAltPBHReceived(), and launch().
The documentation for this class was generated from the following files:
server/CSafeServerSide.h
server/CSafeServerSide.cpp