StartAir_Safe: safe::CSafe Class Reference
safe::CSafe Class Reference
#include <CSafe.h>
Public Member Functions
CSafe (int port)
~CSafe ()
void launch ()
void dataReceived (SimDataEvent &e)
void simQuitted (HANDLE h)
void simStopped (HANDLE h)
void simStarted (HANDLE h)
void latlonaltReceived (HANDLE h, SIMCONNECT_DATA_LATLONALT &d)
void PBHReceived (HANDLE h, SIMCONNECT_DATA_PBH &d)
void latLonAltPBHReceived (HANDLE h, SAFE_DATA_POS &d)
void datagramReceived (SOCKADDR &from, SAFE_RECV &message)
Public Member Functions inherited from safe::ISimListener
virtual ~ISimListener ()
Public Member Functions inherited from UDPReceiver
UDPReceiver (int port)
virtual ~UDPReceiver ()
void boucle ()
Private Attributes
int requid
DataSender ds
Additional Inherited Members
Detailed Description
Definition at line 11 of file CSafe.h.
Constructor & Destructor Documentation
safe::CSafe::CSafe (int port)
Definition at line 15 of file CSafe.cpp.
                              : UDPReceiver(port), ds(0)
         {
         }
safe::CSafe::~CSafe ()
Definition at line 20 of file CSafe.cpp.
         {
         }
Member Function Documentation
void safe::CSafe::datagramReceived (SOCKADDR & from, SAFE_RECV & message) virtual
Implements UDPReceiver.
Definition at line 123 of file CSafe.cpp.
References SAFE_RECV::d, ds, and safe::DataSender::sendPos().
         {
                 //std::cout << "datagramReceived : " << datagram.d.Altitude << " " << d->Latitude << std::endl;
                 //cout << endl << "PLANE LATITUDE = " << datagram.d.Latitude;
                 //cout << endl << "PLANE LONGITUDE = " << datagram.d.Longitude;
                 //cout << endl << "PLANE ALTITUDE = " << datagram.d.Altitude;
                 //cout << endl << "P = " << datagram.d.p;
                 //cout << endl << "B = " << datagram.d.b;
                 //cout << endl << "H = " << datagram.d.h;
                 ds.sendPos(datagram.d);
         }
void safe::CSafe::dataReceived (SimDataEvent & e) virtual
Implements safe::ISimListener.
Definition at line 70 of file CSafe.cpp.
         {
                 //TListDatum d = e.data;                // La structure reçue
                 //if (e.requ->getRequestId() == requid)
                 //{
                 //      // On parcour tous les elements de la structure
                 //      for (TListDatum::iterator it = d.begin(); it != d.end(); it++)
                 //      {
                 //              if (it->first == "PLANE LATITUDE")
                 //              {
                 //                      cout << endl << "PLANE LATITUDE = " << it->second;
                 //                      dataToSend.planeLatitude = it->second;
                 //              }
                 //              else if (it->first == "PLANE LONGITUDE")
                 //              {
                 //                      cout << endl << "PLANE LONGITUDE = " << it->second;
                 //                      dataToSend.planeLongitude = it->second;
                 //              }
                 //              else
                 //              {
                 //                      cout << endl << "Unknown datum :" << it->first;
                 //              }
                 //              // Envoi des données
                 //              SimConnect_SetDataOnSimObject(hSimConnect, DEFINITION_THROTTLE, SIMCONNECT_OBJECT_ID_USER, 0, 0, sizeof(dataToSend), &dataToSend);
                 //              //forex.addSendRecord("SimConnect_SetDataOnSimObject(hSimConnect, DEFINITION_THROTTLE, SIMCONNECT_OBJECT_ID_USER, 0, 0, sizeof(dataToSend), &dataToSend);");
                 //      }
                 //}
                 //else {
                 //      cout << endl << "Unknown request :" << e.requ->getRequestId();
                 //}
         }
void safe::CSafe::latLonAltPBHReceived (HANDLE h, SAFE_DATA_POS & d) virtual
Implements safe::ISimListener.
Definition at line 118 of file CSafe.cpp.
         {
         }
void safe::CSafe::latlonaltReceived (HANDLE h, SIMCONNECT_DATA_LATLONALT & d) virtual
Implements safe::ISimListener.
Definition at line 105 of file CSafe.cpp.
{
                 cout << endl << "PLANE LATITUDE = " << d.Latitude;
                 cout << endl << "PLANE LONGITUDE = " << d.Longitude;
                 cout << endl << "PLANE ALTITUDE = " << d.Altitude;
                 //ds.sendLatLonAlt(d);
         }
void safe::CSafe::launch ()
Definition at line 24 of file CSafe.cpp.
References UDPReceiver::boucle().
Referenced by _tmain().
         {
                 /*
                 list<structVarUnit> l;
                 l.push_back({ "PLANE LATITUDE", "radians" });
                 l.push_back({ "PLANE LONGITUDE", "radians" });
                 // Initialise le receiver pour la reception des données depuis une autre machine
                 sr = SimReceiver(0);
                 // Inscription au type de données reçue
                 //requid = sr.request(l);
                 sr.requestLatLonAlt();
                 sr.requestPBH();
                 //sr.requestAll();
                 sr.addListener(this);
                 ds = DataSender(0);
                 // Boucle de reception pour le traitement des données recues
                 while (!sr.stop())
                 {
                         clock_t tbegin, tend;
                         tbegin = clock();
                         sr.dispatch();
                         //ds.dispatch();
                         tend = clock();
                         if (tend-tbegin !=0) cout << endl << "Temp dispatch :" << (tend - tbegin) << "-------------------------------------- "/ CLOCKS_PER_SEC * 1000;
                         Sleep(1);
                 }
                 */
                 boucle();
         }
void safe::CSafe::PBHReceived (HANDLE h, SIMCONNECT_DATA_PBH & d) virtual
Implements safe::ISimListener.
Definition at line 111 of file CSafe.cpp.
References SIMCONNECT_DATA_PBH::b, SIMCONNECT_DATA_PBH::h, and SIMCONNECT_DATA_PBH::p.
{
                 cout << endl << "P = " << d.p;
                 cout << endl << "B = " << d.b;
                 cout << endl << "H = " << d.h;
                 //ds.sendPBH(d);
         }
void safe::CSafe::simQuitted (HANDLE h) virtual
Implements safe::ISimListener.
Definition at line 66 of file CSafe.cpp.
 { cout << "\nSIM QUIT" << endl; }
void safe::CSafe::simStarted (HANDLE h) virtual
Implements safe::ISimListener.
Definition at line 68 of file CSafe.cpp.
 { cout << "\nSIM START" << endl; }
void safe::CSafe::simStopped (HANDLE h) virtual
Implements safe::ISimListener.
Definition at line 67 of file CSafe.cpp.
 { cout << "\nSIM STOP" << endl; }
Member Data Documentation
DataSender safe::CSafe::ds private
Definition at line 27 of file CSafe.h.
Referenced by datagramReceived().
int safe::CSafe::requid private
Definition at line 26 of file CSafe.h.
The documentation for this class was generated from the following files:
client/CSafe.h
client/CSafe.cpp