StartAir_Safe: Request Class Reference
Request Class Reference
#include <Request.h>
Classes
struct structIdType
Public Member Functions
Request ()
Request (HANDLE hand, std::list< structVarUnit > s)
~Request ()
int getDataId (char *varName)
int getRequestId ()
std::list< structVarUnit > getvarUnitList ()
Protected Member Functions
void addToDataDef ()
void requestDataOnSimObject ()
void addToSubscribedData (int id, structVarUnit vu)
Private Attributes
HANDLE h
int id
std::map< char *, structIdType > data
std::list< structVarUnit > varUnits
Static Private Attributes
static int next_id = 0
Detailed Description
Definition at line 20 of file Request.h.
Constructor & Destructor Documentation
Request::Request ()
Definition at line 10 of file Request.cpp.
 {}
Request::Request (HANDLE hand, std::list< structVarUnit > s)
Definition at line 11 of file Request.cpp.
References addToDataDef(), addToSubscribedData(), h, next_id, and varUnits.
 {
         varUnits = s;
         h = hand;
         id = next_id;
         next_id++;
         int i = 0;
         for (std::list<structVarUnit>::iterator it = s.begin(); it != s.end(); ++it)
         {
                 addToSubscribedData(i, *it);
                 i++;
         }
         addToDataDef();
 }
Request::~Request ()
Definition at line 28 of file Request.cpp.
 {
 }
Member Function Documentation
void Request::addToDataDef () protected
Definition at line 34 of file Request.cpp.
References data, and h.
Referenced by Request().
 {
         for (std::map<char *, structIdType>::iterator it = data.begin(); it != data.end(); ++it)
         {
                 SimConnect_AddToDataDefinition(h, id, it->first, it->second.unitName,SIMCONNECT_DATATYPE_FLOAT32, 0,it->second.id);
                 //SimConnect_AddToDataDefinition(h, id, it->first, it->second.unitName,SIMCONNECT_DATATYPE_FLOAT32, 0,it->second.id);
                 //SimConnect_AddToDataDefinition(h, id, it->first, NULL, SIMCONNECT_DATATYPE_LATLONALT, 0, it->second.id);
         }
 }
void Request::addToSubscribedData (int id, structVarUnit vu) protected
Definition at line 44 of file Request.cpp.
References data, Request::structIdType::id, id, Request::structIdType::unitName, structVarUnit::unitName, and structVarUnit::varName.
Referenced by Request().
{
         structIdType s;
         s.id = id;
         s.unitName = vu.unitName;
         data[vu.varName] = s;
 }
int Request::getDataId (char * varName)
Definition at line 50 of file Request.cpp.
References data.
Referenced by SimDataEvent::SimDataEvent().
{
         return data[varName].id;
 }
int Request::getRequestId ()
Definition at line 53 of file Request.cpp.
References id.
Referenced by safe::SimReceiver::request().
{
         return id;
 }
std::list< structVarUnit > Request::getvarUnitList ()
Definition at line 56 of file Request.cpp.
References varUnits.
Referenced by SimDataEvent::SimDataEvent().
 {
         return varUnits;
 }
void Request::requestDataOnSimObject () protected
Member Data Documentation
std::map<char *, structIdType> Request::data private
Definition at line 37 of file Request.h.
Referenced by addToDataDef(), addToSubscribedData(), and getDataId().
HANDLE Request::h private
Definition at line 34 of file Request.h.
Referenced by addToDataDef(), and Request().
int Request::id private
Definition at line 36 of file Request.h.
Referenced by addToSubscribedData(), and getRequestId().
int Request::next_id = 0 static private
Definition at line 35 of file Request.h.
Referenced by Request().
std::list<structVarUnit> Request::varUnits private
Definition at line 38 of file Request.h.
Referenced by getvarUnitList(), and Request().
The documentation for this class was generated from the following files:
global/Request.h
global/Request.cpp