StartAir_Safe: PRECISION_TIME Class Reference
PRECISION_TIME Class Reference
#include <PRECISION_TIME.h>
Public Member Functions
PRECISION_TIME (void)
~PRECISION_TIME (void)
DWORD GetMilliSec (void)
double GetSec (void)
void InitializeTime (void)
double GetApplTimeSec (void)
Public Attributes
LARGE_INTEGER li
double idiver
double fdiver
Detailed Description
Definition at line 6 of file PRECISION_TIME.h.
Constructor & Destructor Documentation
PRECISION_TIME::PRECISION_TIME (void)
Definition at line 51 of file PRECISION_TIME.cpp.
References InitializeApplicationTime(), and InitializeTime().
 {
    InitializeApplicationTime();
    InitializeTime();
 }
PRECISION_TIME::~PRECISION_TIME (void)
Definition at line 57 of file PRECISION_TIME.cpp.
 {
 }
Member Function Documentation
double PRECISION_TIME::GetApplTimeSec (void)
Definition at line 74 of file PRECISION_TIME.cpp.
References GetSec().
 {
     return(AppTime->GetSec());
 }
DWORD PRECISION_TIME::GetMilliSec (void)
Definition at line 116 of file PRECISION_TIME.cpp.
References idiver, and li.
 {
     double delta;
     DWORD milSec;
     LARGE_INTEGER nli;
     QueryPerformanceCounter(&nli);
     delta = (double)(nli.QuadPart - li.QuadPart) / idiver;
     milSec = (DWORD)delta;
     return(milSec);
 }
double PRECISION_TIME::GetSec (void)
Definition at line 139 of file PRECISION_TIME.cpp.
References fdiver, and li.
Referenced by GetApplTimeSec(), and toexec().
 {
     double Sec;
     LARGE_INTEGER SecNli;
     QueryPerformanceCounter(&SecNli);
     Sec = (double)(SecNli.QuadPart - li.QuadPart) / fdiver;
     return(Sec);
 }
void PRECISION_TIME::InitializeTime (void)
Definition at line 93 of file PRECISION_TIME.cpp.
References fdiver, idiver, and li.
Referenced by PRECISION_TIME().
 {
     fdiver = idiver = 1000.0;
     QueryPerformanceFrequency(&li);                                         // the base time
     idiver = (double)li.QuadPart / 1000.0;
     fdiver =  (double)li.QuadPart;
     QueryPerformanceCounter(&li);
 }
Member Data Documentation
double PRECISION_TIME::fdiver
Definition at line 20 of file PRECISION_TIME.h.
Referenced by GetSec(), and InitializeTime().
double PRECISION_TIME::idiver
Definition at line 19 of file PRECISION_TIME.h.
Referenced by GetMilliSec(), and InitializeTime().
LARGE_INTEGER PRECISION_TIME::li
Definition at line 18 of file PRECISION_TIME.h.
Referenced by GetMilliSec(), GetSec(), and InitializeTime().
The documentation for this class was generated from the following files:
copiercoller/PRECISION_TIME.h
copiercoller/PRECISION_TIME.cpp