StartAir_Safe: UDPReceiver Class Reference
UDPReceiver Class Reference abstract
#include <UDPReceiver.h>
Public Member Functions
UDPReceiver (int port)
virtual ~UDPReceiver ()
void boucle ()
Protected Member Functions
virtual void datagramReceived (SOCKADDR &from, SAFE_RECV &message)=0
Private Attributes
SOCKET sock
int size_buff
Detailed Description
Definition at line 8 of file UDPReceiver.h.
Constructor & Destructor Documentation
UDPReceiver::UDPReceiver (int port)
Definition at line 6 of file UDPReceiver.cpp.
References safe::cfg_Safe, configFile, safe::loadConfig(), size_buff, and sock.
 {
         WSADATA WSAData;
         WSAStartup(MAKEWORD(2, 0), &WSAData);
         sock = socket(AF_INET, SOCK_DGRAM, 0);
         SOCKADDR_IN sin;
         sin.sin_addr.s_addr = INADDR_ANY;
         sin.sin_family = AF_INET;
         sin.sin_port = htons(port);
         bind(sock, (SOCKADDR *)&sin, sizeof(sin));
         listen(sock, 0);
         safe::loadConfig();
         try {
                 if (!safe::cfg_Safe.lookupValue("udpreceiver_buffer_size", size_buff))
                 {
                         std::cerr << "warning : udpreceiver_buffer_size missing in " << configFile << "the listening port will be set to 255" << std::endl;
                         size_buff = 255;
                 }
         }
         catch (const SettingNotFoundException &nfex)
         {
                 std::cerr << "warning : udpreceiver_buffer_size missing in " << configFile << "the listening port will be set to 255" << std::endl;
                 size_buff = 255;
         }
 }
UDPReceiver::~UDPReceiver () virtual
Definition at line 35 of file UDPReceiver.cpp.
References sock.
 {
         closesocket(sock);
         WSACleanup();
         //delete[] buffer;
 }
Member Function Documentation
void UDPReceiver::boucle ()
Definition at line 48 of file UDPReceiver.cpp.
References datagramReceived(), and sock.
Referenced by safe::CSafe::launch().
 {
         //buffer = new char[size_buff];
         char buffer[255];
         SOCKADDR_IN csin;
         int boucle = 0;
         while (1) /* Boucle infinie. Exercice : améliorez ce code. */
         {
                 int sizeof_csin = sizeof(csin);
                 int res = recvfrom(sock, buffer, sizeof(buffer), 0, (SOCKADDR *)&csin, &sizeof_csin);
                 int error = WSAGetLastError();
                 SAFE_RECV * recv = (SAFE_RECV *)buffer;
                 datagramReceived(*(SOCKADDR *)&csin,*recv);
                 //datagramReceived(*(SOCKADDR *)&csin, SAFE_RECV_ID_POS, buffer);
                 //std::cout << res << " " << errno  << " " << error  << std::endl;
                 //boucle++;
                 //if (boucle > 10)
                 //system("pause");
                 //      exit(0);
         }
         closesocket(sock);
 }
virtual void UDPReceiver::datagramReceived (SOCKADDR & from, SAFE_RECV & message) protected pure virtual
Implemented in safe::CSafe.
Referenced by boucle().
Member Data Documentation
int UDPReceiver::size_buff private
Definition at line 19 of file UDPReceiver.h.
Referenced by UDPReceiver().
SOCKET UDPReceiver::sock private
Definition at line 18 of file UDPReceiver.h.
Referenced by boucle(), UDPReceiver(), and ~UDPReceiver().
The documentation for this class was generated from the following files:
client/UDPReceiver.h
client/UDPReceiver.cpp