StartAir_Safe: safe::DataSender Class Reference
safe::DataSender Class Reference
#include <DataSender.h>
Public Member Functions
DataSender ()
DataSender (int numCfg)
~DataSender ()
void sendLatLonAlt (SIMCONNECT_DATA_LATLONALT &d)
void sendPBH (SIMCONNECT_DATA_PBH &d)
void sendPos (SAFE_DATA_POS &d)
Public Member Functions inherited from SimExManager
SimExManager ()
~SimExManager ()
Public Member Functions inherited from SimConnection
SimConnection ()
SimConnection (HANDLE h)
~SimConnection ()
void dispatch ()
Protected Member Functions
void freeze ()
void onRecvSimobjectData (SIMCONNECT_RECV *pData)
void onRecvException (SIMCONNECT_RECV *pData, DWORD cbData)
Protected Member Functions inherited from SimExManager
void addSendRecord (HANDLE hSimConnect, char *c)
char * findSendRecord (DWORD id)
void firstSendRecord (HANDLE h, char *rn)
void lastSendRecord (HANDLE h)
Protected Member Functions inherited from SimConnection
void process (SIMCONNECT_RECV *pData, DWORD cbData)
virtual void onRecvEvent (SIMCONNECT_RECV *pData)
virtual void onRecvQuit (SIMCONNECT_RECV *pData)
Private Attributes
SIMCONNECT_DATA_LATLONALT lla
SIMCONNECT_DATA_PBH pbh
Additional Inherited Members
Static Protected Member Functions inherited from SimConnection
static void CALLBACK dispatchCallback (SIMCONNECT_RECV *pData, DWORD cbData, void *pContext)
Protected Attributes inherited from SimConnection
HANDLE hSimConnect
Detailed Description
Definition at line 8 of file DataSender.h.
Constructor & Destructor Documentation
safe::DataSender::DataSender ()
Definition at line 16 of file DataSender.cpp.
                                : SimConnection(NULL)
         {
         }
safe::DataSender::DataSender (int numCfg)
Definition at line 21 of file DataSender.cpp.
References freeze(), and SimConnection::hSimConnect.
                                          : SimConnection(NULL)
         {
                 list<structVarUnit> l;
                 l.push_back({ "PLANE LATITUDE", "radians" });
                 l.push_back({ "PLANE LONGITUDE", "radians" });
                 //Connection au simulateur local
                 char * nomclient = "Data Sender";
                 if (SUCCEEDED(SimConnect_Open(&hSimConnect, nomclient, NULL, 0, 0, numCfg))) // Local
                 {
                         cout << "\nDataSender connected" << endl;
                         //forex = SimReceiver(hSimConnect);
                         //std::for_each(l.begin(), l.end(), [&](structVarUnit s) {SimConnect_AddToDataDefinition(hSimConnect, DEFINITION_THROTTLE, s.varName, s.unitName); });
                         //SimConnect_AddToDataDefinition(hSimConnect, 100, "PLANE LATITUDE", "Radians");
                         //SimConnect_AddToDataDefinition(hSimConnect, 100, "PLANE LONGITUDE", "Radians");
                         //SimConnect_AddToDataDefinition(hSimConnect, 100, "PLANE ALTITUDE", "Feet");
                         //SimConnect_AddToDataDefinition(hSimConnect, 61, "PLANE PITCH DEGREES", "Radians");
                         //SimConnect_AddToDataDefinition(hSimConnect, 61, "PLANE BANK DEGREES", "Radians");
                         //SimConnect_AddToDataDefinition(hSimConnect, 61, "PLANE HEADING DEGREES TRUE", "Radians");
                         SimConnect_AddToDataDefinition(hSimConnect, 99, "PLANE LATITUDE", "Radians");
                         //forex.addSendRecord(hSimConnect,"a");
                         SimConnect_AddToDataDefinition(hSimConnect, 99, "PLANE LONGITUDE", "Radians");
                         //forex.addSendRecord(hSimConnect,"b");
                         SimConnect_AddToDataDefinition(hSimConnect, 99, "PLANE ALTITUDE", "Feet");
                         //forex.addSendRecord(hSimConnect,"c");
                         //SimConnect_AddToDataDefinition(hSimConnect, 99, "PLANE PITCH DEGREES", "Radians");
                         //SimConnect_AddToDataDefinition(hSimConnect, 99, "PLANE BANK DEGREES", "Radians");
                         //SimConnect_AddToDataDefinition(hSimConnect, 99, "PLANE HEADING DEGREES TRUE", "Radians");
                         SimConnect_AddToDataDefinition(hSimConnect, 99, "PLANE PITCH DEGREES", "degree");
                         SimConnect_AddToDataDefinition(hSimConnect, 99, "PLANE BANK DEGREES", "degree");
                         SimConnect_AddToDataDefinition(hSimConnect, 99, "PLANE HEADING DEGREES TRUE", "degree");
                         freeze();
                         //requestFreezeState();
                 }
         }
safe::DataSender::~DataSender ()
Definition at line 72 of file DataSender.cpp.
         {
         }
Member Function Documentation
void safe::DataSender::freeze () protected
Definition at line 83 of file DataSender.cpp.
References SimExManager::firstSendRecord(), SimConnection::hSimConnect, and SimExManager::lastSendRecord().
Referenced by DataSender().
         {
                 SimConnect_MapClientEventToSimEvent(hSimConnect, 0, "FREEZE_LATITUDE_LONGITUDE_TOGGLE");
                 firstSendRecord(hSimConnect, "freeze()");
                 SimConnect_TransmitClientEvent(hSimConnect, SIMCONNECT_OBJECT_ID_USER, 0, 0, SIMCONNECT_GROUP_PRIORITY_HIGHEST, SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY);
                 SimConnect_MapClientEventToSimEvent(hSimConnect, 1, "FREEZE_ALTITUDE_TOGGLE");
                 SimConnect_TransmitClientEvent(hSimConnect, SIMCONNECT_OBJECT_ID_USER, 1, 0, SIMCONNECT_GROUP_PRIORITY_HIGHEST, SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY);
                 SimConnect_MapClientEventToSimEvent(hSimConnect, 2, "FREEZE_ATTITUDE_TOGGLE");
                 SimConnect_TransmitClientEvent(hSimConnect, SIMCONNECT_OBJECT_ID_USER, 2, 0, SIMCONNECT_GROUP_PRIORITY_HIGHEST, SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY);
                 lastSendRecord(hSimConnect);
         }
void safe::DataSender::onRecvException (SIMCONNECT_RECV * pData, DWORD cbData) protected virtual
Reimplemented from SimConnection.
Definition at line 123 of file DataSender.cpp.
References SimExManager::findSendRecord().
         {
                 SIMCONNECT_RECV_EXCEPTION *except = (SIMCONNECT_RECV_EXCEPTION*)pData;
                 printf("\n\n***** EXCEPTION=%d  SendID=%d  Index=%d  cbData=%d\n", except->dwException, except->dwSendID, except->dwIndex, cbData);
                 // Locate the bad call and print it out
                 char* s = findSendRecord(except->dwSendID);
                 printf("\n%s", s);
         }
void safe::DataSender::onRecvSimobjectData (SIMCONNECT_RECV * pData) protected virtual
Reimplemented from SimConnection.
Definition at line 118 of file DataSender.cpp.
{
         }
void safe::DataSender::sendLatLonAlt (SIMCONNECT_DATA_LATLONALT & d)
Definition at line 95 of file DataSender.cpp.
References SimConnection::hSimConnect.
         {
                 //SimConnect_SetDataOnSimObject(hSimConnect, DEFINITION_THROTTLE, SIMCONNECT_OBJECT_ID_USER, 0, 0, sizeof(dataToSend), &dataToSend);
                 SimConnect_SetDataOnSimObject(hSimConnect, 100, SIMCONNECT_OBJECT_ID_USER, 0, 0, sizeof(d), &d);
                 //forex.addSendRecord("SimConnect_SetDataOnSimObject(hSimConnect, 50, SIMCONNECT_OBJECT_ID_USER, 0, 0, sizeof(d), &d);");
         }
void safe::DataSender::sendPBH (SIMCONNECT_DATA_PBH & d)
Definition at line 101 of file DataSender.cpp.
References SimConnection::hSimConnect.
         {
                 SimConnect_SetDataOnSimObject(hSimConnect, 61, SIMCONNECT_OBJECT_ID_USER, 0, 0, sizeof(d), &d);
                 //forex.addSendRecord("SimConnect_SetDataOnSimObject(hSimConnect, 60, SIMCONNECT_OBJECT_ID_USER, 0, 0, sizeof(d), &d);");
         }
void safe::DataSender::sendPos (SAFE_DATA_POS & d)
Definition at line 107 of file DataSender.cpp.
References SimConnection::hSimConnect.
Referenced by safe::CSafe::datagramReceived().
{
                 SimConnect_SetDataOnSimObject(hSimConnect, 99, SIMCONNECT_OBJECT_ID_USER, 0, 0, sizeof(d), &d);
         }
Member Data Documentation
SIMCONNECT_DATA_LATLONALT safe::DataSender::lla private
Definition at line 19 of file DataSender.h.
SIMCONNECT_DATA_PBH safe::DataSender::pbh private
Definition at line 20 of file DataSender.h.
The documentation for this class was generated from the following files:
global/DataSender.h
global/DataSender.cpp