StartAir_Safe: safe::SimReceiver Class Reference
safe::SimReceiver Class Reference
Allow to retrieve data from the simulator You have to implement ISimListener in order to receive data.
#include <SimReceiver.h>
Public Member Functions
SimReceiver (int numCfg=0)
Create a SimReceiver and a new connection.
~SimReceiver ()
Create a SimReceiver with an existing connection.
int request (std::list< structVarUnit > s)
Subscribe to a list of data.
void requestLatLonAlt ()
Subscribe to latitude, longitude and latitude of user plane Data will be received by using latlonaltReceived() in ISimListener.
void requestPBH ()
Subscribe to pitch, bank and heading of user plane Data will be received by using PBHReceived() in ISimListener.
void requestPos ()
Subscribe to both, latLonAlt and PBH. Data will be received by using latLonAltPBH() in ISimListener.
void close ()
Close the connection with the simulator.
boolean stop ()
void addListener (ISimListener *l)
add l to the listener of this receiver
void removeListener (ISimListener *l)
remove l from the listener list
HANDLE getHandle ()
Get the handle of this receiver.
Public Member Functions inherited from SimExManager
SimExManager ()
~SimExManager ()
Public Member Functions inherited from SimConnection
SimConnection ()
SimConnection (HANDLE h)
~SimConnection ()
void dispatch ()
Protected Member Functions
void onRecvSimobjectData (SIMCONNECT_RECV *pData)
See class SimConnection.
void onRecvEvent (SIMCONNECT_RECV *pData)
See class SimConnection.
void onRecvException (SIMCONNECT_RECV *pData, DWORD cbData)
See class SimConnection.
void onRecvQuit (SIMCONNECT_RECV *pData)
See class SimConnection.
void addToDataDefinition (int defId, std::list< structVarUnit > s)
Create a data definition on the simulator.
void fireDataReceived (SIMCONNECT_RECV_SIMOBJECT_DATA *pObjData)
Tell all listeners that data is received.
void fireSimStart ()
Tell all listeners that the simulation start.
void fireSimStop ()
Tell all listeners that the simulation stop.
void fireSimQuit ()
Tell all listeners that the simulation quit.
void fireLatLonAlt (SIMCONNECT_DATA_LATLONALT &d)
Tell all listeners that data is received.
void firePBH (SIMCONNECT_DATA_PBH &d)
Tell all listeners that data is received.
void firePos (SAFE_DATA_POS &d)
Tell all listeners that data is received.
Protected Member Functions inherited from SimExManager
void addSendRecord (HANDLE hSimConnect, char *c)
char * findSendRecord (DWORD id)
void firstSendRecord (HANDLE h, char *rn)
void lastSendRecord (HANDLE h)
Protected Member Functions inherited from SimConnection
void process (SIMCONNECT_RECV *pData, DWORD cbData)
Private Attributes
Config cfg
boolean quit
boolean latLonAltRequested
boolean PBHRequested
boolean posRequested
std::list< ISimListener * > simListeners
std::map< int, Request > requests
Additional Inherited Members
Static Protected Member Functions inherited from SimConnection
static void CALLBACK dispatchCallback (SIMCONNECT_RECV *pData, DWORD cbData, void *pContext)
Protected Attributes inherited from SimConnection
HANDLE hSimConnect
Detailed Description
Allow to retrieve data from the simulator You have to implement ISimListener in order to receive data.
Definition at line 58 of file SimReceiver.h.
Constructor & Destructor Documentation
safe::SimReceiver::SimReceiver (int numCfg = 0)
Create a SimReceiver and a new connection.
Parameters
numCfg number of the configuration from SimConnect.cfg file
Definition at line 19 of file SimReceiver.cpp.
References safe::EVENT_SIM_START, safe::EVENT_SIM_STOP, and SimConnection::hSimConnect.
                                            : quit(0), SimConnection(NULL), latLonAltRequested(false), PBHRequested(false), posRequested(false)
         {
                 HRESULT hr;
                 char * nomclient = "SimReceiver";
                 if (SUCCEEDED(SimConnect_Open(&hSimConnect, nomclient, NULL, 0, 0, numCfg)))
                 {
                         cout << "\nConnected to Flight Simulator!" << endl;
                         // Request a simulation start event
                         hr = SimConnect_SubscribeToSystemEvent(hSimConnect, EVENT_SIM_START, "SimStart");
                         hr = SimConnect_SubscribeToSystemEvent(hSimConnect, EVENT_SIM_STOP, "SimStop");
                 }
                 else
                 {
                         cout << "Connection failure" << endl;
                         exit(0);
                 }
         }
safe::SimReceiver::~SimReceiver ()
Create a SimReceiver with an existing connection.
Destructor
Definition at line 47 of file SimReceiver.cpp.
         {
         }
Member Function Documentation
void safe::SimReceiver::addListener (ISimListener * l)
add l to the listener of this receiver
Definition at line 205 of file SimReceiver.cpp.
References simListeners.
Referenced by safe::CSafeSS::launch().
{
                 simListeners.push_back(l);
         }
void safe::SimReceiver::addToDataDefinition (int defId, std::list< structVarUnit > s) protected
Create a data definition on the simulator.
Definition at line 197 of file SimReceiver.cpp.
References SimConnection::hSimConnect, structVarUnit::unitName, and structVarUnit::varName.
Referenced by requestLatLonAlt(), requestPBH(), and requestPos().
         {
                 for each (structVarUnit var in s)
                 {
                         SimConnect_AddToDataDefinition(hSimConnect, defId, var.varName, var.unitName);
                 }
         }
void safe::SimReceiver::close ()
Close the connection with the simulator.
Definition at line 52 of file SimReceiver.cpp.
References SimConnection::hSimConnect.
         {
                 if (SUCCEEDED(SimConnect_Close(hSimConnect)))
                 {
                         cout << "Client disconnected" << endl;
                 }
                 else
                 {
                         cout << "\nDisconnection failure\n" << endl;
                 }
         }
void safe::SimReceiver::fireDataReceived (SIMCONNECT_RECV_SIMOBJECT_DATA * pObjData) protected
Tell all listeners that data is received.
Definition at line 219 of file SimReceiver.cpp.
References SimConnection::hSimConnect, requests, and simListeners.
Referenced by onRecvSimobjectData().
         {
                 SimDataEvent e = SimDataEvent(&hSimConnect, &requests[pObjData->dwRequestID], pObjData);
                 std::for_each(simListeners.begin(), simListeners.end(), [&](ISimListener *l) {l->dataReceived(e); });
         }
void safe::SimReceiver::fireLatLonAlt (SIMCONNECT_DATA_LATLONALT & d) protected
Tell all listeners that data is received.
Definition at line 238 of file SimReceiver.cpp.
References SimConnection::hSimConnect, and simListeners.
Referenced by onRecvSimobjectData().
         {
                 std::for_each(simListeners.begin(), simListeners.end(), [&](ISimListener *l) {l->latlonaltReceived(hSimConnect, d); });
         }
void safe::SimReceiver::firePBH (SIMCONNECT_DATA_PBH & d) protected
Tell all listeners that data is received.
Definition at line 242 of file SimReceiver.cpp.
References SimConnection::hSimConnect, and simListeners.
Referenced by onRecvSimobjectData().
         {
                 std::for_each(simListeners.begin(), simListeners.end(), [&](ISimListener *l) {l->PBHReceived(hSimConnect, d); });
         }
void safe::SimReceiver::firePos (SAFE_DATA_POS & d) protected
Tell all listeners that data is received.
Definition at line 247 of file SimReceiver.cpp.
References SimConnection::hSimConnect, and simListeners.
Referenced by onRecvSimobjectData().
         {
                 std::for_each(simListeners.begin(), simListeners.end(), [&](ISimListener *l) {l->latLonAltPBHReceived(hSimConnect, d); });
         }
void safe::SimReceiver::fireSimQuit () protected
Tell all listeners that the simulation quit.
Definition at line 233 of file SimReceiver.cpp.
References SimConnection::hSimConnect, and simListeners.
Referenced by onRecvQuit().
         {
                 std::for_each(simListeners.begin(), simListeners.end(), [&](ISimListener *l) {l->simQuitted(hSimConnect); });
         }
void safe::SimReceiver::fireSimStart () protected
Tell all listeners that the simulation start.
Definition at line 225 of file SimReceiver.cpp.
References SimConnection::hSimConnect, and simListeners.
Referenced by onRecvEvent().
         {
                 std::for_each(simListeners.begin(), simListeners.end(), [&](ISimListener *l) {l->simStarted(hSimConnect); });
         }
void safe::SimReceiver::fireSimStop () protected
Tell all listeners that the simulation stop.
Definition at line 229 of file SimReceiver.cpp.
References SimConnection::hSimConnect, and simListeners.
Referenced by onRecvEvent().
         {
                 std::for_each(simListeners.begin(), simListeners.end(), [&](ISimListener *l) {l->simStopped(hSimConnect); });
         }
HANDLE safe::SimReceiver::getHandle ()
Get the handle of this receiver.
Returns
The handle
Definition at line 215 of file SimReceiver.cpp.
References SimConnection::hSimConnect.
         {
                 return hSimConnect;
         }
void safe::SimReceiver::onRecvEvent (SIMCONNECT_RECV * pData) protected virtual
See class SimConnection.
Reimplemented from SimConnection.
Definition at line 107 of file SimReceiver.cpp.
References safe::EVENT_SIM_START, safe::EVENT_SIM_STOP, fireSimStart(), fireSimStop(), SimConnection::hSimConnect, latLonAltRequested, PBHRequested, and posRequested.
{
                         //cout << "SIMCONNECT_RECV_ID_EVENT" << endl;
                         SIMCONNECT_RECV_EVENT *evt = (SIMCONNECT_RECV_EVENT*)pData;
                         switch (evt->uEventID)
{
                                 case EVENT_SIM_START:
                                         fireSimStart();
                                         //cout << "EVENT_SIM_START" << endl;
                                         // Make the call for data every sim frame, but only when it changes and
                                         // only that data that has changed
                                         /*for (std::map<int, Request>::iterator it = requests.begin(); it != requests.end(); it++)
{
                                                 SimConnect_RequestDataOnSimObject(hSimConnect, it->first, it->first, SIMCONNECT_OBJECT_ID_USER, SIMCONNECT_PERIOD_SIM_FRAME, SIMCONNECT_DATA_REQUEST_FLAG_CHANGED | SIMCONNECT_DATA_REQUEST_FLAG_TAGGED);
                                                 //hr = SimConnect_RequestDataOnSimObject(hSimConnect, REQUEST_PDR, DEFINITION_PDR, SIMCONNECT_OBJECT_ID_USER, SIMCONNECT_PERIOD_SIM_FRAME, SIMCONNECT_DATA_REQUEST_FLAG_CHANGED | SIMCONNECT_DATA_REQUEST_FLAG_TAGGED);
                                         }*/
                                         if (latLonAltRequested){ SimConnect_RequestDataOnSimObject(hSimConnect, 50, 50, SIMCONNECT_OBJECT_ID_USER, SIMCONNECT_PERIOD_VISUAL_FRAME, SIMCONNECT_DATA_REQUEST_FLAG_CHANGED); }
                                         if (PBHRequested){ SimConnect_RequestDataOnSimObject(hSimConnect, 60, 60, SIMCONNECT_OBJECT_ID_USER, SIMCONNECT_PERIOD_VISUAL_FRAME, SIMCONNECT_DATA_REQUEST_FLAG_CHANGED); }
                                         if (posRequested){ SimConnect_RequestDataOnSimObject(hSimConnect, 70, 70, SIMCONNECT_OBJECT_ID_USER, SIMCONNECT_PERIOD_VISUAL_FRAME, SIMCONNECT_DATA_REQUEST_FLAG_CHANGED); }
                                         break;
                                 case EVENT_SIM_STOP:
                                         fireSimStop();
                                         break;
                                 default:
                                         //cout << "EVENT UNKNOW" << endl;
                                         break;
                         }
         }
void safe::SimReceiver::onRecvException (SIMCONNECT_RECV * pData, DWORD cbData) protected virtual
See class SimConnection.
Reimplemented from SimConnection.
Definition at line 136 of file SimReceiver.cpp.
References SimExManager::findSendRecord().
         {
                 SIMCONNECT_RECV_EXCEPTION *except = (SIMCONNECT_RECV_EXCEPTION*)pData;
                 printf("\n\n***** EXCEPTION=%d  SendID=%d  Index=%d  cbData=%d\n", except->dwException, except->dwSendID, except->dwIndex, cbData);
                 // Locate the bad call and print it out
                 char* s = findSendRecord(except->dwSendID);
                 printf("\n%s", s);
         }
void safe::SimReceiver::onRecvQuit (SIMCONNECT_RECV * pData) protected virtual
See class SimConnection.
Reimplemented from SimConnection.
Definition at line 145 of file SimReceiver.cpp.
References fireSimQuit(), and quit.
         {
                 fireSimQuit();
                 quit = 1;
         }
void safe::SimReceiver::onRecvSimobjectData (SIMCONNECT_RECV * pData) protected virtual
See class SimConnection.
Reimplemented from SimConnection.
Definition at line 68 of file SimReceiver.cpp.
References fireDataReceived(), fireLatLonAlt(), firePBH(), and firePos().
{
                 //DataSender::boucle++;
                 SIMCONNECT_RECV_SIMOBJECT_DATA *pObjData = (SIMCONNECT_RECV_SIMOBJECT_DATA*)pData;
                 //cout << endl << DataSender::boucle << "-> " << pObjData->dwRequestID;
                 if (pObjData->dwRequestID == 50)
                 {
                         SIMCONNECT_DATA_LATLONALT*  d = (SIMCONNECT_DATA_LATLONALT*)&pObjData->dwData;
                         fireLatLonAlt(*d);
                 }
                 else if (pObjData->dwRequestID == 60)
                 {
                         //SIMCONNECT_DATA_LATLONALT*  d = (SIMCONNECT_DATA_LATLONALT*)&pObjData->dwData;
                         SIMCONNECT_DATA_PBH * d = (SIMCONNECT_DATA_PBH*)&pObjData->dwData;
                         firePBH(*d);
                 }
                 else if (pObjData->dwRequestID == 70)
                 {
                         //SIMCONNECT_DATA_LATLONALT*  d = (SIMCONNECT_DATA_LATLONALT*)&pObjData->dwData;
                         SAFE_DATA_POS * d = (SAFE_DATA_POS*)&pObjData->dwData;
                         //fireLatLonAlt(d->d1);
                         //firePBH(d->d2);
                         firePos(*d);
                 }
                 else
                 {
                         fireDataReceived(pObjData);
                 }
                 //      StructDatum *pS = (StructDatum*)&pObjData->dwData;
         }
void safe::SimReceiver::removeListener (ISimListener * l)
remove l from the listener list
Definition at line 208 of file SimReceiver.cpp.
References simListeners.
{
                 simListeners.remove(l);
                 /*      else {
                                 // handle the case
                                 cout << "Could not unregister the specified listener object as it is not registered." << std::endl;
                                 }*/
         }
int safe::SimReceiver::request (std::list< structVarUnit > s)
Subscribe to a list of data.
Parameters
s set datas data that you want to retrieve for this request Data will be received by using dataReceived() in ISimListener
Returns
l'id de la requete
Definition at line 39 of file SimReceiver.cpp.
References Request::getRequestId(), SimConnection::hSimConnect, and requests.
         {
                 Request r = Request(hSimConnect, s);
                 requests[r.getRequestId()] = r;
                 return r.getRequestId();
         }
void safe::SimReceiver::requestLatLonAlt ()
Subscribe to latitude, longitude and latitude of user plane Data will be received by using latlonaltReceived() in ISimListener.
Definition at line 151 of file SimReceiver.cpp.
References addToDataDefinition(), and latLonAltRequested.
{
                 //SimConnect_AddToDataDefinition(hSimConnect, 50, "PLANE LATITUDE", "Radians");
                 //SimConnect_AddToDataDefinition(hSimConnect, 50, "PLANE LONGITUDE", "Radians");
                 //SimConnect_AddToDataDefinition(hSimConnect, 50, "PLANE ALTITUDE", "Feet");
                 list<structVarUnit> l;
                 l.push_back({ "PLANE LATITUDE", "Radians" });
                 l.push_back({ "PLANE LONGITUDE", "Radians" });
                 l.push_back({ "PLANE ALTITUDE", "Feet" });
                 this->addToDataDefinition(50, l);
                 latLonAltRequested = true;
         }
void safe::SimReceiver::requestPBH ()
Subscribe to pitch, bank and heading of user plane Data will be received by using PBHReceived() in ISimListener.
Definition at line 164 of file SimReceiver.cpp.
References addToDataDefinition(), and PBHRequested.
{
                 //SimConnect_AddToDataDefinition(hSimConnect, 60, "struct LATLONALTPBH", NULL, SIMCONNECT_DATATYPE_LATLONALT, 0, 0);
                 //SimConnect_AddToDataDefinition(hSimConnect, 60, "PLANE PITCH DEGREES", "Radians"/*, SIMCONNECT_DATATYPE_LATLONALT, 0, 0*/);
                 //SimConnect_AddToDataDefinition(hSimConnect, 60, "PLANE BANK DEGREES", "Radians"/*, SIMCONNECT_DATATYPE_LATLONALT, 0, 0*/);
                 //SimConnect_AddToDataDefinition(hSimConnect, 60, "PLANE HEADING DEGREES TRUE", "Radians"/*, SIMCONNECT_DATATYPE_LATLONALT, 0, 0*/);
                 list<structVarUnit> l;
                 l.push_back({ "PLANE PITCH DEGREES", "Radians" });
                 l.push_back({ "PLANE BANK DEGREES", "Radians" });
                 l.push_back({ "PLANE HEADING DEGREES TRUE", "Radians" });
                 this->addToDataDefinition(60, l);
                 PBHRequested = true;
         }
void safe::SimReceiver::requestPos ()
Subscribe to both, latLonAlt and PBH. Data will be received by using latLonAltPBH() in ISimListener.
Definition at line 176 of file SimReceiver.cpp.
References addToDataDefinition(), and posRequested.
Referenced by safe::CSafeSS::launch().
{
                 //SimConnect_AddToDataDefinition(hSimConnect, 70, "PLANE LATITUDE", "Radians");
                 //SimConnect_AddToDataDefinition(hSimConnect, 70, "PLANE LONGITUDE", "Radians");
                 //SimConnect_AddToDataDefinition(hSimConnect, 70, "PLANE ALTITUDE", "Feet");
                 //SimConnect_AddToDataDefinition(hSimConnect, 70, "PLANE PITCH DEGREES", "Radians"/*, SIMCONNECT_DATATYPE_LATLONALT, 0, 0*/);
                 //SimConnect_AddToDataDefinition(hSimConnect, 70, "PLANE BANK DEGREES", "Radians"/*, SIMCONNECT_DATATYPE_LATLONALT, 0, 0*/);
                 //SimConnect_AddToDataDefinition(hSimConnect, 70, "PLANE HEADING DEGREES TRUE", "Radians"/*, SIMCONNECT_DATATYPE_LATLONALT, 0, 0*/);
                 list<structVarUnit> l;
                 l.push_back({ "PLANE LATITUDE", "Radians" });
                 l.push_back({ "PLANE LONGITUDE", "Radians" });
                 l.push_back({ "PLANE ALTITUDE", "Feet" });
                 //l.push_back({ "PLANE PITCH DEGREES", "Radians" });
                 //l.push_back({ "PLANE BANK DEGREES", "Radians" });
                 //l.push_back({ "PLANE HEADING DEGREES TRUE", "Radians" });
                 l.push_back({ "PLANE PITCH DEGREES", "degree" });
                 l.push_back({ "PLANE BANK DEGREES", "degree" });
                 l.push_back({ "PLANE HEADING DEGREES TRUE", "degree" });
                 this->addToDataDefinition(70, l);
                 posRequested = true;
         }
boolean safe::SimReceiver::stop ()
Returns
true if the simulator has quit
Definition at line 63 of file SimReceiver.cpp.
References quit.
Referenced by safe::CSafeSS::launch().
{
                 return quit;
         }
Member Data Documentation
Config safe::SimReceiver::cfg private
The configuration from config.h for SimReceiver
Definition at line 61 of file SimReceiver.h.
boolean safe::SimReceiver::latLonAltRequested private
True if requestLatLonAlt() has been called
Definition at line 63 of file SimReceiver.h.
Referenced by onRecvEvent(), and requestLatLonAlt().
boolean safe::SimReceiver::PBHRequested private
True if requestPBH() has been called
Definition at line 64 of file SimReceiver.h.
Referenced by onRecvEvent(), and requestPBH().
boolean safe::SimReceiver::posRequested private
True if requestPos() has been called
Definition at line 65 of file SimReceiver.h.
Referenced by onRecvEvent(), and requestPos().
boolean safe::SimReceiver::quit private
True if the simulator quit
Definition at line 62 of file SimReceiver.h.
Referenced by onRecvQuit(), and stop().
std::map<int, Request> safe::SimReceiver::requests private
The id of the request ans the Request created when request() is called
Definition at line 67 of file SimReceiver.h.
Referenced by fireDataReceived(), and request().
std::list<ISimListener*> safe::SimReceiver::simListeners private
Listener list
Definition at line 66 of file SimReceiver.h.
Referenced by addListener(), fireDataReceived(), fireLatLonAlt(), firePBH(), firePos(), fireSimQuit(), fireSimStart(), fireSimStop(), and removeListener().
The documentation for this class was generated from the following files:
global/SimReceiver.h
global/SimReceiver.cpp