StartAir_Safe: SimConnection Class Reference
SimConnection Class Reference
#include <SimConnection.h>
Public Member Functions
SimConnection ()
SimConnection (HANDLE h)
~SimConnection ()
void dispatch ()
Protected Member Functions
void process (SIMCONNECT_RECV *pData, DWORD cbData)
virtual void onRecvSimobjectData (SIMCONNECT_RECV *pData)
virtual void onRecvEvent (SIMCONNECT_RECV *pData)
virtual void onRecvException (SIMCONNECT_RECV *pData, DWORD cbData)
virtual void onRecvQuit (SIMCONNECT_RECV *pData)
Static Protected Member Functions
static void CALLBACK dispatchCallback (SIMCONNECT_RECV *pData, DWORD cbData, void *pContext)
Protected Attributes
HANDLE hSimConnect
Detailed Description
Definition at line 6 of file SimConnection.h.
Constructor & Destructor Documentation
SimConnection::SimConnection ()
Definition at line 4 of file SimConnection.cpp.
 {
 }
SimConnection::SimConnection (HANDLE h)
Definition at line 8 of file SimConnection.cpp.
                                      : hSimConnect(h)
 {
 }
SimConnection::~SimConnection ()
Definition at line 12 of file SimConnection.cpp.
 {
 }
Member Function Documentation
void SimConnection::dispatch ()
Definition at line 16 of file SimConnection.cpp.
References dispatchCallback(), hSimConnect, and SimConnect_CallDispatch().
Referenced by safe::CSafeSS::launch().
 {
         SimConnect_CallDispatch(hSimConnect, SimConnection::dispatchCallback, this);
 }
void SimConnection::dispatchCallback (SIMCONNECT_RECV * pData, DWORD cbData, void * pContext) static protected
Definition at line 21 of file SimConnection.cpp.
References process().
Referenced by dispatch().
 {
         SimConnection *pThis = reinterpret_cast<SimConnection*>(pContext);
         pThis->process(pData, cbData);
 }
void SimConnection::onRecvEvent (SIMCONNECT_RECV * pData) protected virtual
Reimplemented in safe::SimReceiver.
Definition at line 30 of file SimConnection.cpp.
Referenced by process().
{
         std::cout << std::endl << "onRecvEvent";
 }
void SimConnection::onRecvException (SIMCONNECT_RECV * pData, DWORD cbData) protected virtual
Reimplemented in safe::SimReceiver, and safe::DataSender.
Definition at line 33 of file SimConnection.cpp.
Referenced by process().
{
         std::cout << std::endl << "onRecvException";
 }
void SimConnection::onRecvQuit (SIMCONNECT_RECV * pData) protected virtual
Reimplemented in safe::SimReceiver.
Definition at line 36 of file SimConnection.cpp.
Referenced by process().
{
         std::cout << std::endl << "onRecvQuit";
 }
void SimConnection::onRecvSimobjectData (SIMCONNECT_RECV * pData) protected virtual
Reimplemented in safe::SimReceiver, and safe::DataSender.
Definition at line 27 of file SimConnection.cpp.
Referenced by process().
{
         std::cout << std::endl <<"onRecvSimobjectData";
 }
void SimConnection::process (SIMCONNECT_RECV * pData, DWORD cbData) protected
Definition at line 40 of file SimConnection.cpp.
References SIMCONNECT_RECV::dwID, onRecvEvent(), onRecvException(), onRecvQuit(), onRecvSimobjectData(), SIMCONNECT_RECV_ID_EVENT, SIMCONNECT_RECV_ID_EXCEPTION, SIMCONNECT_RECV_ID_QUIT, and SIMCONNECT_RECV_ID_SIMOBJECT_DATA.
Referenced by dispatchCallback().
 {
         //HRESULT hr;
         switch (pData->dwID)
         {
                 case SIMCONNECT_RECV_ID_EVENT:
                         onRecvEvent(pData);
                         break;
                 case SIMCONNECT_RECV_ID_SIMOBJECT_DATA:
                         onRecvSimobjectData(pData);
                         break;
                 case SIMCONNECT_RECV_ID_EXCEPTION:
                         onRecvException(pData, cbData);
                         break;
                 case SIMCONNECT_RECV_ID_QUIT:
                         onRecvQuit(pData);
                         break;
                 default:
                         printf("\nUnknown dwID: %d", pData->dwID);
                         break;
         }
 }
Member Data Documentation
HANDLE SimConnection::hSimConnect protected
Definition at line 18 of file SimConnection.h.
Referenced by safe::SimReceiver::addToDataDefinition(), safe::SimReceiver::close(), safe::DataSender::DataSender(), dispatch(), safe::SimReceiver::fireDataReceived(), safe::SimReceiver::fireLatLonAlt(), safe::SimReceiver::firePBH(), safe::SimReceiver::firePos(), safe::SimReceiver::fireSimQuit(), safe::SimReceiver::fireSimStart(), safe::SimReceiver::fireSimStop(), safe::DataSender::freeze(), safe::SimReceiver::getHandle(), safe::SimReceiver::onRecvEvent(), safe::SimReceiver::request(), safe::DataSender::sendLatLonAlt(), safe::DataSender::sendPBH(), safe::DataSender::sendPos(), and safe::SimReceiver::SimReceiver().
The documentation for this class was generated from the following files:
global/SimConnection.h
global/SimConnection.cpp