StartAir_Safe: copiercoller/maincopiercoller.cpp File Reference
maincopiercoller.cpp File Reference
#include <iostream>
#include <utility>
#include <thread>
#include <chrono>
#include <functional>
#include <atomic>
#include <ctime>
#include "PRECISION_TIME.h"
#include "../../libconfig-1.4.9/lib/libconfig.h++"
Functions
void f1 (int n)
void f2 (int &n)
void toexec ()
int main ()
Variables
bool end = false
Function Documentation
void f1 (int n)
Definition at line 11 of file maincopiercoller.cpp.
Referenced by face::face().
 {
         for (int i = 0; i < 5; ++i) {
                 std::cout << "Thread 1 executing\n";
                 ++n;
                 std::this_thread::sleep_for(std::chrono::milliseconds(10));
         }
 }
void f2 (int & n)
Definition at line 20 of file maincopiercoller.cpp.
Referenced by face::face().
 {
         for (int i = 0; i < 5; ++i) {
                 std::cout << "Thread 2 executing\n";
                 ++n;
                 std::this_thread::sleep_for(std::chrono::milliseconds(10));
         }
 }
int main ()
Definition at line 58 of file maincopiercoller.cpp.
 {
         Config cfg;
         try
         {
                 cfg.readFile("../../safe.cfg");
         }
         catch (const FileIOException &fioex)
         {
                 std::cerr << "File not found." << std::endl;
                 return(EXIT_FAILURE);
         }
         catch (const ParseException &pex)
         {
                 std::cerr << "Parse error at " << pex.getFile() << ":" << pex.getLine()
                         << " - " << pex.getError() << std::endl;
                 return(EXIT_FAILURE);
         }
 }
void toexec ()
Definition at line 31 of file maincopiercoller.cpp.
References end, and PRECISION_TIME::GetSec().
 {
         int frame = 0;
         int imgsec =60;
         PRECISION_TIME pt;
         while (!end) {
                 int temps = ((1 / (float)imgsec) * 1000);
                 std::this_thread::sleep_for(std::chrono::milliseconds(temps));
                 frame++;
                 //std::cout << "time : " << (tend - tbegin) << " frame : " << frame << std::endl;
                 //std::cout << "time : " << pt.GetSec() << "frame : " << frame  <<std::endl;
                 if (pt.GetSec() >= 1)
                 {
                         std::cout << "nb frame : " << frame << "   time =" << pt.GetSec() << std::endl;
                         frame = 0;
                         pt = PRECISION_TIME();
                 }
         }
 }
Variable Documentation
bool end = false
Definition at line 29 of file maincopiercoller.cpp.
Referenced by objloader::load(), main(), and toexec().