StartAir_Safe: safe Namespace Reference
safe Namespace Reference
Classes
class CSafeSS
class DataSender
class ISimListener
class SimReceiver
Allow to retrieve data from the simulator You have to implement ISimListener in order to receive data.
class CSafe
Enumerations
enum SIM_EVENT { EVENT_SIM_START, EVENT_SIM_STOP }
simulator event constant
Functions
static void loadConfig ()
Variables
static Config cfg_Safe
Detailed Description
namespace which contain class for the project StartAir Safe
Enumeration Type Documentation
enum safe::SIM_EVENT
simulator event constant
SIM_EVENT are used to subscribing to system event
Enumerator
EVENT_SIM_START
EVENT_SIM_STOP
Definition at line 47 of file SimReceiver.h.
{
                 EVENT_SIM_START,
                 EVENT_SIM_STOP
         };
Function Documentation
static void safe::loadConfig () static
Definition at line 17 of file config.h.
References cfg_Safe, and configFile.
Referenced by _tmain(), safe::DataSender::DataSender(), safe::CSafeSS::launch(), and UDPReceiver::UDPReceiver().
{
                 try
                 {
                         cfg_Safe.readFile(configFile);
                 }
                 catch (const FileIOException &fioex)
                 {
                         std::cerr << "I/O error while reading file. " << "Is " << "\"" <<configFile <<  "\""  << " existing ?" << std::endl;
                         system("pause");
                         exit(EXIT_FAILURE);
                 }
                 catch (const ParseException &pex)
                 {
                         std::cerr << "Parse error at " << pex.getFile() << ":" << pex.getLine()
                                 << " - " << pex.getError() << std::endl;
                         exit(EXIT_FAILURE);
                 }
         }
Variable Documentation
Config safe::cfg_Safe static
Definition at line 15 of file config.h.
Referenced by _tmain(), safe::DataSender::DataSender(), safe::DataSender::freeze(), safe::CSafeSS::launch(), loadConfig(), safe::DataSender::sendPos(), and UDPReceiver::UDPReceiver().