StartAir_Safe: inc/SimConnect.h File Reference
SimConnect.h File Reference
#include <float.h>
#include <Windows.h>
Classes
struct SIMCONNECT_RECV
struct SIMCONNECT_RECV_EXCEPTION
struct SIMCONNECT_RECV_OPEN
struct SIMCONNECT_RECV_QUIT
struct SIMCONNECT_RECV_EVENT
struct SIMCONNECT_RECV_EVENT_FILENAME
struct SIMCONNECT_RECV_EVENT_OBJECT_ADDREMOVE
struct SIMCONNECT_RECV_EVENT_FRAME
struct SIMCONNECT_RECV_EVENT_MULTIPLAYER_SERVER_STARTED
struct SIMCONNECT_RECV_EVENT_MULTIPLAYER_CLIENT_STARTED
struct SIMCONNECT_RECV_EVENT_MULTIPLAYER_SESSION_ENDED
struct SIMCONNECT_DATA_RACE_RESULT
struct SIMCONNECT_RECV_EVENT_RACE_END
struct SIMCONNECT_RECV_EVENT_RACE_LAP
struct SIMCONNECT_RECV_SIMOBJECT_DATA
struct SIMCONNECT_RECV_SIMOBJECT_DATA_BYTYPE
struct SIMCONNECT_RECV_CLIENT_DATA
struct SIMCONNECT_RECV_WEATHER_OBSERVATION
struct SIMCONNECT_RECV_CLOUD_STATE
struct SIMCONNECT_RECV_ASSIGNED_OBJECT_ID
struct SIMCONNECT_RECV_RESERVED_KEY
struct SIMCONNECT_RECV_SYSTEM_STATE
struct SIMCONNECT_RECV_CUSTOM_ACTION
struct SIMCONNECT_RECV_EVENT_WEATHER_MODE
struct SIMCONNECT_RECV_FACILITIES_LIST
struct SIMCONNECT_DATA_FACILITY_AIRPORT
struct SIMCONNECT_RECV_AIRPORT_LIST
struct SIMCONNECT_DATA_FACILITY_WAYPOINT
struct SIMCONNECT_RECV_WAYPOINT_LIST
struct SIMCONNECT_DATA_FACILITY_NDB
struct SIMCONNECT_RECV_NDB_LIST
struct SIMCONNECT_DATA_FACILITY_VOR
struct SIMCONNECT_RECV_VOR_LIST
struct SIMCONNECT_DATA_INITPOSITION
struct SIMCONNECT_DATA_MARKERSTATE
struct SIMCONNECT_DATA_WAYPOINT
struct SIMCONNECT_DATA_LATLONALT
struct SIMCONNECT_DATA_XYZ
Macros
#define DWORD_MAX 0xFFFFFFFF
#define SIMCONNECTAPI extern "C" HRESULT __stdcall
Typedefs
typedef DWORD SIMCONNECT_OBJECT_ID
typedef DWORD SIMCONNECT_VOR_FLAGS
typedef DWORD SIMCONNECT_WAYPOINT_FLAGS
typedef DWORD SIMCONNECT_EVENT_FLAG
typedef DWORD SIMCONNECT_DATA_REQUEST_FLAG
typedef DWORD SIMCONNECT_DATA_SET_FLAG
typedef DWORD SIMCONNECT_CREATE_CLIENT_DATA_FLAG
typedef DWORD SIMCONNECT_CLIENT_DATA_REQUEST_FLAG
typedef DWORD SIMCONNECT_CLIENT_DATA_SET_FLAG
typedef DWORD SIMCONNECT_VIEW_SYSTEM_EVENT_DATA
typedef DWORD SIMCONNECT_SOUND_SYSTEM_EVENT_DATA
typedef DWORD SIMCONNECT_NOTIFICATION_GROUP_ID
typedef DWORD SIMCONNECT_INPUT_GROUP_ID
typedef DWORD SIMCONNECT_DATA_DEFINITION_ID
typedef DWORD SIMCONNECT_DATA_REQUEST_ID
typedef DWORD SIMCONNECT_CLIENT_EVENT_ID
typedef DWORD SIMCONNECT_CLIENT_DATA_ID
typedef DWORD SIMCONNECT_CLIENT_DATA_DEFINITION_ID
typedef void(CALLBACK * DispatchProc)(SIMCONNECT_RECV *pData, DWORD cbData, void *pContext)
Enumerations
enum SIMCONNECT_RECV_ID {
SIMCONNECT_RECV_ID_NULL, SIMCONNECT_RECV_ID_EXCEPTION, SIMCONNECT_RECV_ID_OPEN, SIMCONNECT_RECV_ID_QUIT,
SIMCONNECT_RECV_ID_EVENT, SIMCONNECT_RECV_ID_EVENT_OBJECT_ADDREMOVE, SIMCONNECT_RECV_ID_EVENT_FILENAME, SIMCONNECT_RECV_ID_EVENT_FRAME,
SIMCONNECT_RECV_ID_SIMOBJECT_DATA, SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE, SIMCONNECT_RECV_ID_WEATHER_OBSERVATION, SIMCONNECT_RECV_ID_CLOUD_STATE,
SIMCONNECT_RECV_ID_ASSIGNED_OBJECT_ID, SIMCONNECT_RECV_ID_RESERVED_KEY, SIMCONNECT_RECV_ID_CUSTOM_ACTION, SIMCONNECT_RECV_ID_SYSTEM_STATE,
SIMCONNECT_RECV_ID_CLIENT_DATA, SIMCONNECT_RECV_ID_EVENT_WEATHER_MODE, SIMCONNECT_RECV_ID_AIRPORT_LIST, SIMCONNECT_RECV_ID_VOR_LIST,
SIMCONNECT_RECV_ID_NDB_LIST, SIMCONNECT_RECV_ID_WAYPOINT_LIST, SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SERVER_STARTED, SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_CLIENT_STARTED,
SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SESSION_ENDED, SIMCONNECT_RECV_ID_EVENT_RACE_END, SIMCONNECT_RECV_ID_EVENT_RACE_LAP
}
enum SIMCONNECT_DATATYPE {
SIMCONNECT_DATATYPE_INVALID, SIMCONNECT_DATATYPE_INT32, SIMCONNECT_DATATYPE_INT64, SIMCONNECT_DATATYPE_FLOAT32,
SIMCONNECT_DATATYPE_FLOAT64, SIMCONNECT_DATATYPE_STRING8, SIMCONNECT_DATATYPE_STRING32, SIMCONNECT_DATATYPE_STRING64,
SIMCONNECT_DATATYPE_STRING128, SIMCONNECT_DATATYPE_STRING256, SIMCONNECT_DATATYPE_STRING260, SIMCONNECT_DATATYPE_STRINGV,
SIMCONNECT_DATATYPE_INITPOSITION, SIMCONNECT_DATATYPE_MARKERSTATE, SIMCONNECT_DATATYPE_WAYPOINT, SIMCONNECT_DATATYPE_LATLONALT,
SIMCONNECT_DATATYPE_XYZ, SIMCONNECT_DATATYPE_MAX
}
enum SIMCONNECT_EXCEPTION {
SIMCONNECT_EXCEPTION_NONE, SIMCONNECT_EXCEPTION_ERROR, SIMCONNECT_EXCEPTION_SIZE_MISMATCH, SIMCONNECT_EXCEPTION_UNRECOGNIZED_ID,
SIMCONNECT_EXCEPTION_UNOPENED, SIMCONNECT_EXCEPTION_VERSION_MISMATCH, SIMCONNECT_EXCEPTION_TOO_MANY_GROUPS, SIMCONNECT_EXCEPTION_NAME_UNRECOGNIZED,
SIMCONNECT_EXCEPTION_TOO_MANY_EVENT_NAMES, SIMCONNECT_EXCEPTION_EVENT_ID_DUPLICATE, SIMCONNECT_EXCEPTION_TOO_MANY_MAPS, SIMCONNECT_EXCEPTION_TOO_MANY_OBJECTS,
SIMCONNECT_EXCEPTION_TOO_MANY_REQUESTS, SIMCONNECT_EXCEPTION_WEATHER_INVALID_PORT, SIMCONNECT_EXCEPTION_WEATHER_INVALID_METAR, SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_GET_OBSERVATION,
SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_CREATE_STATION, SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_REMOVE_STATION, SIMCONNECT_EXCEPTION_INVALID_DATA_TYPE, SIMCONNECT_EXCEPTION_INVALID_DATA_SIZE,
SIMCONNECT_EXCEPTION_DATA_ERROR, SIMCONNECT_EXCEPTION_INVALID_ARRAY, SIMCONNECT_EXCEPTION_CREATE_OBJECT_FAILED, SIMCONNECT_EXCEPTION_LOAD_FLIGHTPLAN_FAILED,
SIMCONNECT_EXCEPTION_OPERATION_INVALID_FOR_OBJECT_TYPE, SIMCONNECT_EXCEPTION_ILLEGAL_OPERATION, SIMCONNECT_EXCEPTION_ALREADY_SUBSCRIBED, SIMCONNECT_EXCEPTION_INVALID_ENUM,
SIMCONNECT_EXCEPTION_DEFINITION_ERROR, SIMCONNECT_EXCEPTION_DUPLICATE_ID, SIMCONNECT_EXCEPTION_DATUM_ID, SIMCONNECT_EXCEPTION_OUT_OF_BOUNDS,
SIMCONNECT_EXCEPTION_ALREADY_CREATED, SIMCONNECT_EXCEPTION_OBJECT_OUTSIDE_REALITY_BUBBLE, SIMCONNECT_EXCEPTION_OBJECT_CONTAINER, SIMCONNECT_EXCEPTION_OBJECT_AI,
SIMCONNECT_EXCEPTION_OBJECT_ATC, SIMCONNECT_EXCEPTION_OBJECT_SCHEDULE
}
enum SIMCONNECT_SIMOBJECT_TYPE {
SIMCONNECT_SIMOBJECT_TYPE_USER, SIMCONNECT_SIMOBJECT_TYPE_ALL, SIMCONNECT_SIMOBJECT_TYPE_AIRCRAFT, SIMCONNECT_SIMOBJECT_TYPE_HELICOPTER,
SIMCONNECT_SIMOBJECT_TYPE_BOAT, SIMCONNECT_SIMOBJECT_TYPE_GROUND
}
enum SIMCONNECT_STATE { SIMCONNECT_STATE_OFF, SIMCONNECT_STATE_ON }
enum SIMCONNECT_PERIOD {
SIMCONNECT_PERIOD_NEVER, SIMCONNECT_PERIOD_ONCE, SIMCONNECT_PERIOD_VISUAL_FRAME, SIMCONNECT_PERIOD_SIM_FRAME,
SIMCONNECT_PERIOD_SECOND
}
enum SIMCONNECT_MISSION_END { SIMCONNECT_MISSION_FAILED, SIMCONNECT_MISSION_CRASHED, SIMCONNECT_MISSION_SUCCEEDED }
enum SIMCONNECT_CLIENT_DATA_PERIOD {
SIMCONNECT_CLIENT_DATA_PERIOD_NEVER, SIMCONNECT_CLIENT_DATA_PERIOD_ONCE, SIMCONNECT_CLIENT_DATA_PERIOD_VISUAL_FRAME, SIMCONNECT_CLIENT_DATA_PERIOD_ON_SET,
SIMCONNECT_CLIENT_DATA_PERIOD_SECOND
}
enum SIMCONNECT_TEXT_TYPE {
SIMCONNECT_TEXT_TYPE_SCROLL_BLACK, SIMCONNECT_TEXT_TYPE_SCROLL_WHITE, SIMCONNECT_TEXT_TYPE_SCROLL_RED, SIMCONNECT_TEXT_TYPE_SCROLL_GREEN,
SIMCONNECT_TEXT_TYPE_SCROLL_BLUE, SIMCONNECT_TEXT_TYPE_SCROLL_YELLOW, SIMCONNECT_TEXT_TYPE_SCROLL_MAGENTA, SIMCONNECT_TEXT_TYPE_SCROLL_CYAN,
SIMCONNECT_TEXT_TYPE_PRINT_BLACK =0x0100, SIMCONNECT_TEXT_TYPE_PRINT_WHITE, SIMCONNECT_TEXT_TYPE_PRINT_RED, SIMCONNECT_TEXT_TYPE_PRINT_GREEN,
SIMCONNECT_TEXT_TYPE_PRINT_BLUE, SIMCONNECT_TEXT_TYPE_PRINT_YELLOW, SIMCONNECT_TEXT_TYPE_PRINT_MAGENTA, SIMCONNECT_TEXT_TYPE_PRINT_CYAN,
SIMCONNECT_TEXT_TYPE_MENU =0x0200
}
enum SIMCONNECT_TEXT_RESULT {
SIMCONNECT_TEXT_RESULT_MENU_SELECT_1, SIMCONNECT_TEXT_RESULT_MENU_SELECT_2, SIMCONNECT_TEXT_RESULT_MENU_SELECT_3, SIMCONNECT_TEXT_RESULT_MENU_SELECT_4,
SIMCONNECT_TEXT_RESULT_MENU_SELECT_5, SIMCONNECT_TEXT_RESULT_MENU_SELECT_6, SIMCONNECT_TEXT_RESULT_MENU_SELECT_7, SIMCONNECT_TEXT_RESULT_MENU_SELECT_8,
SIMCONNECT_TEXT_RESULT_MENU_SELECT_9, SIMCONNECT_TEXT_RESULT_MENU_SELECT_10, SIMCONNECT_TEXT_RESULT_DISPLAYED = 0x00010000, SIMCONNECT_TEXT_RESULT_QUEUED,
SIMCONNECT_TEXT_RESULT_REMOVED, SIMCONNECT_TEXT_RESULT_REPLACED, SIMCONNECT_TEXT_RESULT_TIMEOUT
}
enum SIMCONNECT_WEATHER_MODE { SIMCONNECT_WEATHER_MODE_THEME, SIMCONNECT_WEATHER_MODE_RWW, SIMCONNECT_WEATHER_MODE_CUSTOM, SIMCONNECT_WEATHER_MODE_GLOBAL }
enum SIMCONNECT_FACILITY_LIST_TYPE {
SIMCONNECT_FACILITY_LIST_TYPE_AIRPORT, SIMCONNECT_FACILITY_LIST_TYPE_WAYPOINT, SIMCONNECT_FACILITY_LIST_TYPE_NDB, SIMCONNECT_FACILITY_LIST_TYPE_VOR,
SIMCONNECT_FACILITY_LIST_TYPE_COUNT
}
Functions
SIMCONNECTAPI SimConnect_MapClientEventToSimEvent (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID EventID, const char *EventName="")
SIMCONNECTAPI SimConnect_TransmitClientEvent (HANDLE hSimConnect, SIMCONNECT_OBJECT_ID ObjectID, SIMCONNECT_CLIENT_EVENT_ID EventID, DWORD dwData, SIMCONNECT_NOTIFICATION_GROUP_ID GroupID, SIMCONNECT_EVENT_FLAG Flags)
SIMCONNECTAPI SimConnect_SetSystemEventState (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID EventID, SIMCONNECT_STATE dwState)
SIMCONNECTAPI SimConnect_AddClientEventToNotificationGroup (HANDLE hSimConnect, SIMCONNECT_NOTIFICATION_GROUP_ID GroupID, SIMCONNECT_CLIENT_EVENT_ID EventID, BOOL bMaskable=FALSE)
SIMCONNECTAPI SimConnect_RemoveClientEvent (HANDLE hSimConnect, SIMCONNECT_NOTIFICATION_GROUP_ID GroupID, SIMCONNECT_CLIENT_EVENT_ID EventID)
SIMCONNECTAPI SimConnect_SetNotificationGroupPriority (HANDLE hSimConnect, SIMCONNECT_NOTIFICATION_GROUP_ID GroupID, DWORD uPriority)
SIMCONNECTAPI SimConnect_ClearNotificationGroup (HANDLE hSimConnect, SIMCONNECT_NOTIFICATION_GROUP_ID GroupID)
SIMCONNECTAPI SimConnect_RequestNotificationGroup (HANDLE hSimConnect, SIMCONNECT_NOTIFICATION_GROUP_ID GroupID, DWORD dwReserved=0, DWORD Flags=0)
SIMCONNECTAPI SimConnect_AddToDataDefinition (HANDLE hSimConnect, SIMCONNECT_DATA_DEFINITION_ID DefineID, const char *DatumName, const char *UnitsName, SIMCONNECT_DATATYPE DatumType=SIMCONNECT_DATATYPE_FLOAT64, float fEpsilon=0, DWORD DatumID=SIMCONNECT_UNUSED)
SIMCONNECTAPI SimConnect_ClearDataDefinition (HANDLE hSimConnect, SIMCONNECT_DATA_DEFINITION_ID DefineID)
SIMCONNECTAPI SimConnect_RequestDataOnSimObject (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, SIMCONNECT_DATA_DEFINITION_ID DefineID, SIMCONNECT_OBJECT_ID ObjectID, SIMCONNECT_PERIOD Period, SIMCONNECT_DATA_REQUEST_FLAG Flags=0, DWORD origin=0, DWORD interval=0, DWORD limit=0)
SIMCONNECTAPI SimConnect_RequestDataOnSimObjectType (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, SIMCONNECT_DATA_DEFINITION_ID DefineID, DWORD dwRadiusMeters, SIMCONNECT_SIMOBJECT_TYPE type)
SIMCONNECTAPI SimConnect_SetDataOnSimObject (HANDLE hSimConnect, SIMCONNECT_DATA_DEFINITION_ID DefineID, SIMCONNECT_OBJECT_ID ObjectID, SIMCONNECT_DATA_SET_FLAG Flags, DWORD ArrayCount, DWORD cbUnitSize, void *pDataSet)
SIMCONNECTAPI SimConnect_MapInputEventToClientEvent (HANDLE hSimConnect, SIMCONNECT_INPUT_GROUP_ID GroupID, const char *szInputDefinition, SIMCONNECT_CLIENT_EVENT_ID DownEventID, DWORD DownValue=0, SIMCONNECT_CLIENT_EVENT_ID UpEventID=(SIMCONNECT_CLIENT_EVENT_ID) SIMCONNECT_UNUSED, DWORD UpValue=0, BOOL bMaskable=FALSE)
SIMCONNECTAPI SimConnect_SetInputGroupPriority (HANDLE hSimConnect, SIMCONNECT_INPUT_GROUP_ID GroupID, DWORD uPriority)
SIMCONNECTAPI SimConnect_RemoveInputEvent (HANDLE hSimConnect, SIMCONNECT_INPUT_GROUP_ID GroupID, const char *szInputDefinition)
SIMCONNECTAPI SimConnect_ClearInputGroup (HANDLE hSimConnect, SIMCONNECT_INPUT_GROUP_ID GroupID)
SIMCONNECTAPI SimConnect_SetInputGroupState (HANDLE hSimConnect, SIMCONNECT_INPUT_GROUP_ID GroupID, DWORD dwState)
SIMCONNECTAPI SimConnect_RequestReservedKey (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID EventID, const char *szKeyChoice1="", const char *szKeyChoice2="", const char *szKeyChoice3="")
SIMCONNECTAPI SimConnect_SubscribeToSystemEvent (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID EventID, const char *SystemEventName)
SIMCONNECTAPI SimConnect_UnsubscribeFromSystemEvent (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID EventID)
SIMCONNECTAPI SimConnect_WeatherRequestInterpolatedObservation (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, float lat, float lon, float alt)
SIMCONNECTAPI SimConnect_WeatherRequestObservationAtStation (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, const char *szICAO)
SIMCONNECTAPI SimConnect_WeatherRequestObservationAtNearestStation (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, float lat, float lon)
SIMCONNECTAPI SimConnect_WeatherCreateStation (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, const char *szICAO, const char *szName, float lat, float lon, float alt)
SIMCONNECTAPI SimConnect_WeatherRemoveStation (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, const char *szICAO)
SIMCONNECTAPI SimConnect_WeatherSetObservation (HANDLE hSimConnect, DWORD Seconds, const char *szMETAR)
SIMCONNECTAPI SimConnect_WeatherSetModeServer (HANDLE hSimConnect, DWORD dwPort, DWORD dwSeconds)
SIMCONNECTAPI SimConnect_WeatherSetModeTheme (HANDLE hSimConnect, const char *szThemeName)
SIMCONNECTAPI SimConnect_WeatherSetModeGlobal (HANDLE hSimConnect)
SIMCONNECTAPI SimConnect_WeatherSetModeCustom (HANDLE hSimConnect)
SIMCONNECTAPI SimConnect_WeatherSetDynamicUpdateRate (HANDLE hSimConnect, DWORD dwRate)
SIMCONNECTAPI SimConnect_WeatherRequestCloudState (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, float minLat, float minLon, float minAlt, float maxLat, float maxLon, float maxAlt, DWORD dwFlags=0)
SIMCONNECTAPI SimConnect_WeatherCreateThermal (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, float lat, float lon, float alt, float radius, float height, float coreRate=3.0f, float coreTurbulence=0.05f, float sinkRate=3.0f, float sinkTurbulence=0.2f, float coreSize=0.4f, float coreTransitionSize=0.1f, float sinkLayerSize=0.4f, float sinkTransitionSize=0.1f)
SIMCONNECTAPI SimConnect_WeatherRemoveThermal (HANDLE hSimConnect, SIMCONNECT_OBJECT_ID ObjectID)
SIMCONNECTAPI SimConnect_AICreateParkedATCAircraft (HANDLE hSimConnect, const char *szContainerTitle, const char *szTailNumber, const char *szAirportID, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_AICreateEnrouteATCAircraft (HANDLE hSimConnect, const char *szContainerTitle, const char *szTailNumber, int iFlightNumber, const char *szFlightPlanPath, double dFlightPlanPosition, BOOL bTouchAndGo, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_AICreateNonATCAircraft (HANDLE hSimConnect, const char *szContainerTitle, const char *szTailNumber, SIMCONNECT_DATA_INITPOSITION InitPos, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_AICreateSimulatedObject (HANDLE hSimConnect, const char *szContainerTitle, SIMCONNECT_DATA_INITPOSITION InitPos, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_AIReleaseControl (HANDLE hSimConnect, SIMCONNECT_OBJECT_ID ObjectID, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_AIRemoveObject (HANDLE hSimConnect, SIMCONNECT_OBJECT_ID ObjectID, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_AISetAircraftFlightPlan (HANDLE hSimConnect, SIMCONNECT_OBJECT_ID ObjectID, const char *szFlightPlanPath, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_ExecuteMissionAction (HANDLE hSimConnect, const GUID guidInstanceId)
SIMCONNECTAPI SimConnect_CompleteCustomMissionAction (HANDLE hSimConnect, const GUID guidInstanceId)
SIMCONNECTAPI SimConnect_Close (HANDLE hSimConnect)
SIMCONNECTAPI SimConnect_RetrieveString (SIMCONNECT_RECV *pData, DWORD cbData, void *pStringV, char **pszString, DWORD *pcbString)
SIMCONNECTAPI SimConnect_GetLastSentPacketID (HANDLE hSimConnect, DWORD *pdwError)
SIMCONNECTAPI SimConnect_Open (HANDLE *phSimConnect, LPCSTR szName, HWND hWnd, DWORD UserEventWin32, HANDLE hEventHandle, DWORD ConfigIndex)
SIMCONNECTAPI SimConnect_CallDispatch (HANDLE hSimConnect, DispatchProc pfcnDispatch, void *pContext)
SIMCONNECTAPI SimConnect_GetNextDispatch (HANDLE hSimConnect, SIMCONNECT_RECV **ppData, DWORD *pcbData)
SIMCONNECTAPI SimConnect_RequestResponseTimes (HANDLE hSimConnect, DWORD nCount, float *fElapsedSeconds)
SIMCONNECTAPI SimConnect_InsertString (char *pDest, DWORD cbDest, void **ppEnd, DWORD *pcbStringV, const char *pSource)
SIMCONNECTAPI SimConnect_CameraSetRelative6DOF (HANDLE hSimConnect, float fDeltaX, float fDeltaY, float fDeltaZ, float fPitchDeg, float fBankDeg, float fHeadingDeg)
SIMCONNECTAPI SimConnect_MenuAddItem (HANDLE hSimConnect, const char *szMenuItem, SIMCONNECT_CLIENT_EVENT_ID MenuEventID, DWORD dwData)
SIMCONNECTAPI SimConnect_MenuDeleteItem (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID MenuEventID)
SIMCONNECTAPI SimConnect_MenuAddSubItem (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID MenuEventID, const char *szMenuItem, SIMCONNECT_CLIENT_EVENT_ID SubMenuEventID, DWORD dwData)
SIMCONNECTAPI SimConnect_MenuDeleteSubItem (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID MenuEventID, const SIMCONNECT_CLIENT_EVENT_ID SubMenuEventID)
SIMCONNECTAPI SimConnect_RequestSystemState (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, const char *szState)
SIMCONNECTAPI SimConnect_SetSystemState (HANDLE hSimConnect, const char *szState, DWORD dwInteger, float fFloat, const char *szString)
SIMCONNECTAPI SimConnect_MapClientDataNameToID (HANDLE hSimConnect, const char *szClientDataName, SIMCONNECT_CLIENT_DATA_ID ClientDataID)
SIMCONNECTAPI SimConnect_CreateClientData (HANDLE hSimConnect, SIMCONNECT_CLIENT_DATA_ID ClientDataID, DWORD dwSize, SIMCONNECT_CREATE_CLIENT_DATA_FLAG Flags)
SIMCONNECTAPI SimConnect_AddToClientDataDefinition (HANDLE hSimConnect, SIMCONNECT_CLIENT_DATA_DEFINITION_ID DefineID, DWORD dwOffset, DWORD dwSizeOrType, float fEpsilon=0, DWORD DatumID=SIMCONNECT_UNUSED)
SIMCONNECTAPI SimConnect_ClearClientDataDefinition (HANDLE hSimConnect, SIMCONNECT_CLIENT_DATA_DEFINITION_ID DefineID)
SIMCONNECTAPI SimConnect_RequestClientData (HANDLE hSimConnect, SIMCONNECT_CLIENT_DATA_ID ClientDataID, SIMCONNECT_DATA_REQUEST_ID RequestID, SIMCONNECT_CLIENT_DATA_DEFINITION_ID DefineID, SIMCONNECT_CLIENT_DATA_PERIOD Period=SIMCONNECT_CLIENT_DATA_PERIOD_ONCE, SIMCONNECT_CLIENT_DATA_REQUEST_FLAG Flags=0, DWORD origin=0, DWORD interval=0, DWORD limit=0)
SIMCONNECTAPI SimConnect_SetClientData (HANDLE hSimConnect, SIMCONNECT_CLIENT_DATA_ID ClientDataID, SIMCONNECT_CLIENT_DATA_DEFINITION_ID DefineID, SIMCONNECT_CLIENT_DATA_SET_FLAG Flags, DWORD dwReserved, DWORD cbUnitSize, void *pDataSet)
SIMCONNECTAPI SimConnect_FlightLoad (HANDLE hSimConnect, const char *szFileName)
SIMCONNECTAPI SimConnect_FlightSave (HANDLE hSimConnect, const char *szFileName, const char *szTitle, const char *szDescription, DWORD Flags)
SIMCONNECTAPI SimConnect_FlightPlanLoad (HANDLE hSimConnect, const char *szFileName)
SIMCONNECTAPI SimConnect_Text (HANDLE hSimConnect, SIMCONNECT_TEXT_TYPE type, float fTimeSeconds, SIMCONNECT_CLIENT_EVENT_ID EventID, DWORD cbUnitSize, void *pDataSet)
SIMCONNECTAPI SimConnect_SubscribeToFacilities (HANDLE hSimConnect, SIMCONNECT_FACILITY_LIST_TYPE type, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_UnsubscribeToFacilities (HANDLE hSimConnect, SIMCONNECT_FACILITY_LIST_TYPE type)
SIMCONNECTAPI SimConnect_RequestFacilitiesList (HANDLE hSimConnect, SIMCONNECT_FACILITY_LIST_TYPE type, SIMCONNECT_DATA_REQUEST_ID RequestID)
Variables
static const DWORD SIMCONNECT_UNUSED = DWORD_MAX
static const DWORD SIMCONNECT_OBJECT_ID_USER = 0
static const float SIMCONNECT_CAMERA_IGNORE_FIELD = FLT_MAX
static const DWORD SIMCONNECT_CLIENTDATA_MAX_SIZE = 8192
static const DWORD SIMCONNECT_GROUP_PRIORITY_HIGHEST = 1
static const DWORD SIMCONNECT_GROUP_PRIORITY_HIGHEST_MASKABLE = 10000000
static const DWORD SIMCONNECT_GROUP_PRIORITY_STANDARD = 1900000000
static const DWORD SIMCONNECT_GROUP_PRIORITY_DEFAULT = 2000000000
static const DWORD SIMCONNECT_GROUP_PRIORITY_LOWEST = 4000000000
static const DWORD MAX_METAR_LENGTH = 2000
static const float MAX_THERMAL_SIZE = 100000
static const float MAX_THERMAL_RATE = 1000
static const DWORD INITPOSITION_AIRSPEED_CRUISE = -1
static const DWORD INITPOSITION_AIRSPEED_KEEP = -2
static const DWORD SIMCONNECT_CLIENTDATATYPE_INT8 = -1
static const DWORD SIMCONNECT_CLIENTDATATYPE_INT16 = -2
static const DWORD SIMCONNECT_CLIENTDATATYPE_INT32 = -3
static const DWORD SIMCONNECT_CLIENTDATATYPE_INT64 = -4
static const DWORD SIMCONNECT_CLIENTDATATYPE_FLOAT32 = -5
static const DWORD SIMCONNECT_CLIENTDATATYPE_FLOAT64 = -6
static const DWORD SIMCONNECT_CLIENTDATAOFFSET_AUTO = -1
static const DWORD SIMCONNECT_OPEN_CONFIGINDEX_LOCAL = -1
static const DWORD SIMCONNECT_RECV_ID_VOR_LIST_HAS_NAV_SIGNAL = 0x00000001
static const DWORD SIMCONNECT_RECV_ID_VOR_LIST_HAS_LOCALIZER = 0x00000002
static const DWORD SIMCONNECT_RECV_ID_VOR_LIST_HAS_GLIDE_SLOPE = 0x00000004
static const DWORD SIMCONNECT_RECV_ID_VOR_LIST_HAS_DME = 0x00000008
static const DWORD SIMCONNECT_WAYPOINT_NONE = 0x00
static const DWORD SIMCONNECT_WAYPOINT_SPEED_REQUESTED = 0x04
static const DWORD SIMCONNECT_WAYPOINT_THROTTLE_REQUESTED = 0x08
static const DWORD SIMCONNECT_WAYPOINT_COMPUTE_VERTICAL_SPEED = 0x10
static const DWORD SIMCONNECT_WAYPOINT_ALTITUDE_IS_AGL = 0x20
static const DWORD SIMCONNECT_WAYPOINT_ON_GROUND = 0x00100000
static const DWORD SIMCONNECT_WAYPOINT_REVERSE = 0x00200000
static const DWORD SIMCONNECT_WAYPOINT_WRAP_TO_FIRST = 0x00400000
static const DWORD SIMCONNECT_EVENT_FLAG_DEFAULT = 0x00000000
static const DWORD SIMCONNECT_EVENT_FLAG_FAST_REPEAT_TIMER = 0x00000001
static const DWORD SIMCONNECT_EVENT_FLAG_SLOW_REPEAT_TIMER = 0x00000002
static const DWORD SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY = 0x00000010
static const DWORD SIMCONNECT_DATA_REQUEST_FLAG_DEFAULT = 0x00000000
static const DWORD SIMCONNECT_DATA_REQUEST_FLAG_CHANGED = 0x00000001
static const DWORD SIMCONNECT_DATA_REQUEST_FLAG_TAGGED = 0x00000002
static const DWORD SIMCONNECT_DATA_SET_FLAG_DEFAULT = 0x00000000
static const DWORD SIMCONNECT_DATA_SET_FLAG_TAGGED = 0x00000001
static const DWORD SIMCONNECT_CREATE_CLIENT_DATA_FLAG_DEFAULT = 0x00000000
static const DWORD SIMCONNECT_CREATE_CLIENT_DATA_FLAG_READ_ONLY = 0x00000001
static const DWORD SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_DEFAULT = 0x00000000
static const DWORD SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_CHANGED = 0x00000001
static const DWORD SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_TAGGED = 0x00000002
static const DWORD SIMCONNECT_CLIENT_DATA_SET_FLAG_DEFAULT = 0x00000000
static const DWORD SIMCONNECT_CLIENT_DATA_SET_FLAG_TAGGED = 0x00000001
static const DWORD SIMCONNECT_VIEW_SYSTEM_EVENT_DATA_COCKPIT_2D = 0x00000001
static const DWORD SIMCONNECT_VIEW_SYSTEM_EVENT_DATA_COCKPIT_VIRTUAL = 0x00000002
static const DWORD SIMCONNECT_VIEW_SYSTEM_EVENT_DATA_ORTHOGONAL = 0x00000004
static const DWORD SIMCONNECT_SOUND_SYSTEM_EVENT_DATA_MASTER = 0x00000001
static const int SIMCONNECT_CLOUD_STATE_ARRAY_WIDTH = 64
static const int SIMCONNECT_CLOUD_STATE_ARRAY_SIZE = SIMCONNECT_CLOUD_STATE_ARRAY_WIDTH*SIMCONNECT_CLOUD_STATE_ARRAY_WIDTH
Macro Definition Documentation
#define DWORD_MAX 0xFFFFFFFF
Definition at line 25 of file SimConnect.h.
#define SIMCONNECTAPI extern "C" HRESULT __stdcall
Definition at line 666 of file SimConnect.h.
Typedef Documentation
typedef void(CALLBACK * DispatchProc)(SIMCONNECT_RECV *pData, DWORD cbData, void *pContext)
Definition at line 670 of file SimConnect.h.
typedef DWORD SIMCONNECT_CLIENT_DATA_DEFINITION_ID
Definition at line 363 of file SimConnect.h.
typedef DWORD SIMCONNECT_CLIENT_DATA_ID
Definition at line 362 of file SimConnect.h.
typedef DWORD SIMCONNECT_CLIENT_DATA_REQUEST_FLAG
Definition at line 325 of file SimConnect.h.
typedef DWORD SIMCONNECT_CLIENT_DATA_SET_FLAG
Definition at line 332 of file SimConnect.h.
typedef DWORD SIMCONNECT_CLIENT_EVENT_ID
Definition at line 361 of file SimConnect.h.
typedef DWORD SIMCONNECT_CREATE_CLIENT_DATA_FLAG
Definition at line 319 of file SimConnect.h.
typedef DWORD SIMCONNECT_DATA_DEFINITION_ID
Definition at line 358 of file SimConnect.h.
typedef DWORD SIMCONNECT_DATA_REQUEST_FLAG
Definition at line 306 of file SimConnect.h.
typedef DWORD SIMCONNECT_DATA_REQUEST_ID
Definition at line 359 of file SimConnect.h.
typedef DWORD SIMCONNECT_DATA_SET_FLAG
Definition at line 313 of file SimConnect.h.
typedef DWORD SIMCONNECT_EVENT_FLAG
Definition at line 298 of file SimConnect.h.
typedef DWORD SIMCONNECT_INPUT_GROUP_ID
Definition at line 357 of file SimConnect.h.
typedef DWORD SIMCONNECT_NOTIFICATION_GROUP_ID
Definition at line 356 of file SimConnect.h.
typedef DWORD SIMCONNECT_OBJECT_ID
Definition at line 31 of file SimConnect.h.
typedef DWORD SIMCONNECT_SOUND_SYSTEM_EVENT_DATA
Definition at line 345 of file SimConnect.h.
typedef DWORD SIMCONNECT_VIEW_SYSTEM_EVENT_DATA
Definition at line 338 of file SimConnect.h.
typedef DWORD SIMCONNECT_VOR_FLAGS
Definition at line 276 of file SimConnect.h.
typedef DWORD SIMCONNECT_WAYPOINT_FLAGS
Definition at line 286 of file SimConnect.h.
Enumeration Type Documentation
enum SIMCONNECT_CLIENT_DATA_PERIOD
Enumerator
SIMCONNECT_CLIENT_DATA_PERIOD_NEVER
SIMCONNECT_CLIENT_DATA_PERIOD_ONCE
SIMCONNECT_CLIENT_DATA_PERIOD_VISUAL_FRAME
SIMCONNECT_CLIENT_DATA_PERIOD_ON_SET
SIMCONNECT_CLIENT_DATA_PERIOD_SECOND
Definition at line 215 of file SimConnect.h.
{
     SIMCONNECT_CLIENT_DATA_PERIOD_NEVER,
     SIMCONNECT_CLIENT_DATA_PERIOD_ONCE,
     SIMCONNECT_CLIENT_DATA_PERIOD_VISUAL_FRAME,
     SIMCONNECT_CLIENT_DATA_PERIOD_ON_SET,
     SIMCONNECT_CLIENT_DATA_PERIOD_SECOND,
 };
enum SIMCONNECT_DATATYPE
Enumerator
SIMCONNECT_DATATYPE_INVALID
SIMCONNECT_DATATYPE_INT32
SIMCONNECT_DATATYPE_INT64
SIMCONNECT_DATATYPE_FLOAT32
SIMCONNECT_DATATYPE_FLOAT64
SIMCONNECT_DATATYPE_STRING8
SIMCONNECT_DATATYPE_STRING32
SIMCONNECT_DATATYPE_STRING64
SIMCONNECT_DATATYPE_STRING128
SIMCONNECT_DATATYPE_STRING256
SIMCONNECT_DATATYPE_STRING260
SIMCONNECT_DATATYPE_STRINGV
SIMCONNECT_DATATYPE_INITPOSITION
SIMCONNECT_DATATYPE_MARKERSTATE
SIMCONNECT_DATATYPE_WAYPOINT
SIMCONNECT_DATATYPE_LATLONALT
SIMCONNECT_DATATYPE_XYZ
SIMCONNECT_DATATYPE_MAX
Definition at line 116 of file SimConnect.h.
{
     SIMCONNECT_DATATYPE_INVALID,        // invalid data type
     SIMCONNECT_DATATYPE_INT32,          // 32-bit integer number
     SIMCONNECT_DATATYPE_INT64,          // 64-bit integer number
     SIMCONNECT_DATATYPE_FLOAT32,        // 32-bit floating-point number (float)
     SIMCONNECT_DATATYPE_FLOAT64,        // 64-bit floating-point number (double)
     SIMCONNECT_DATATYPE_STRING8,        // 8-byte string
     SIMCONNECT_DATATYPE_STRING32,       // 32-byte string
     SIMCONNECT_DATATYPE_STRING64,       // 64-byte string
     SIMCONNECT_DATATYPE_STRING128,      // 128-byte string
     SIMCONNECT_DATATYPE_STRING256,      // 256-byte string
     SIMCONNECT_DATATYPE_STRING260,      // 260-byte string
     SIMCONNECT_DATATYPE_STRINGV,        // variable-length string
     SIMCONNECT_DATATYPE_INITPOSITION,   // see SIMCONNECT_DATA_INITPOSITION
     SIMCONNECT_DATATYPE_MARKERSTATE,    // see SIMCONNECT_DATA_MARKERSTATE
     SIMCONNECT_DATATYPE_WAYPOINT,       // see SIMCONNECT_DATA_WAYPOINT
     SIMCONNECT_DATATYPE_LATLONALT,      // see SIMCONNECT_DATA_LATLONALT
     SIMCONNECT_DATATYPE_XYZ,            // see SIMCONNECT_DATA_XYZ
     SIMCONNECT_DATATYPE_MAX             // enum limit
 };
enum SIMCONNECT_EXCEPTION
Enumerator
SIMCONNECT_EXCEPTION_NONE
SIMCONNECT_EXCEPTION_ERROR
SIMCONNECT_EXCEPTION_SIZE_MISMATCH
SIMCONNECT_EXCEPTION_UNRECOGNIZED_ID
SIMCONNECT_EXCEPTION_UNOPENED
SIMCONNECT_EXCEPTION_VERSION_MISMATCH
SIMCONNECT_EXCEPTION_TOO_MANY_GROUPS
SIMCONNECT_EXCEPTION_NAME_UNRECOGNIZED
SIMCONNECT_EXCEPTION_TOO_MANY_EVENT_NAMES
SIMCONNECT_EXCEPTION_EVENT_ID_DUPLICATE
SIMCONNECT_EXCEPTION_TOO_MANY_MAPS
SIMCONNECT_EXCEPTION_TOO_MANY_OBJECTS
SIMCONNECT_EXCEPTION_TOO_MANY_REQUESTS
SIMCONNECT_EXCEPTION_WEATHER_INVALID_PORT
SIMCONNECT_EXCEPTION_WEATHER_INVALID_METAR
SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_GET_OBSERVATION
SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_CREATE_STATION
SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_REMOVE_STATION
SIMCONNECT_EXCEPTION_INVALID_DATA_TYPE
SIMCONNECT_EXCEPTION_INVALID_DATA_SIZE
SIMCONNECT_EXCEPTION_DATA_ERROR
SIMCONNECT_EXCEPTION_INVALID_ARRAY
SIMCONNECT_EXCEPTION_CREATE_OBJECT_FAILED
SIMCONNECT_EXCEPTION_LOAD_FLIGHTPLAN_FAILED
SIMCONNECT_EXCEPTION_OPERATION_INVALID_FOR_OBJECT_TYPE
SIMCONNECT_EXCEPTION_ILLEGAL_OPERATION
SIMCONNECT_EXCEPTION_ALREADY_SUBSCRIBED
SIMCONNECT_EXCEPTION_INVALID_ENUM
SIMCONNECT_EXCEPTION_DEFINITION_ERROR
SIMCONNECT_EXCEPTION_DUPLICATE_ID
SIMCONNECT_EXCEPTION_DATUM_ID
SIMCONNECT_EXCEPTION_OUT_OF_BOUNDS
SIMCONNECT_EXCEPTION_ALREADY_CREATED
SIMCONNECT_EXCEPTION_OBJECT_OUTSIDE_REALITY_BUBBLE
SIMCONNECT_EXCEPTION_OBJECT_CONTAINER
SIMCONNECT_EXCEPTION_OBJECT_AI
SIMCONNECT_EXCEPTION_OBJECT_ATC
SIMCONNECT_EXCEPTION_OBJECT_SCHEDULE
Definition at line 140 of file SimConnect.h.
{
     SIMCONNECT_EXCEPTION_NONE,
     SIMCONNECT_EXCEPTION_ERROR,
     SIMCONNECT_EXCEPTION_SIZE_MISMATCH,
     SIMCONNECT_EXCEPTION_UNRECOGNIZED_ID,
     SIMCONNECT_EXCEPTION_UNOPENED,
     SIMCONNECT_EXCEPTION_VERSION_MISMATCH,
     SIMCONNECT_EXCEPTION_TOO_MANY_GROUPS,
     SIMCONNECT_EXCEPTION_NAME_UNRECOGNIZED,
     SIMCONNECT_EXCEPTION_TOO_MANY_EVENT_NAMES,
     SIMCONNECT_EXCEPTION_EVENT_ID_DUPLICATE,
     SIMCONNECT_EXCEPTION_TOO_MANY_MAPS,
     SIMCONNECT_EXCEPTION_TOO_MANY_OBJECTS,
     SIMCONNECT_EXCEPTION_TOO_MANY_REQUESTS,
     SIMCONNECT_EXCEPTION_WEATHER_INVALID_PORT,
     SIMCONNECT_EXCEPTION_WEATHER_INVALID_METAR,
     SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_GET_OBSERVATION,
     SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_CREATE_STATION,
     SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_REMOVE_STATION,
     SIMCONNECT_EXCEPTION_INVALID_DATA_TYPE,
     SIMCONNECT_EXCEPTION_INVALID_DATA_SIZE,
     SIMCONNECT_EXCEPTION_DATA_ERROR,
     SIMCONNECT_EXCEPTION_INVALID_ARRAY,
     SIMCONNECT_EXCEPTION_CREATE_OBJECT_FAILED,
     SIMCONNECT_EXCEPTION_LOAD_FLIGHTPLAN_FAILED,
     SIMCONNECT_EXCEPTION_OPERATION_INVALID_FOR_OBJECT_TYPE,
     SIMCONNECT_EXCEPTION_ILLEGAL_OPERATION,
     SIMCONNECT_EXCEPTION_ALREADY_SUBSCRIBED,
     SIMCONNECT_EXCEPTION_INVALID_ENUM,
     SIMCONNECT_EXCEPTION_DEFINITION_ERROR,
     SIMCONNECT_EXCEPTION_DUPLICATE_ID,
     SIMCONNECT_EXCEPTION_DATUM_ID,
     SIMCONNECT_EXCEPTION_OUT_OF_BOUNDS,
     SIMCONNECT_EXCEPTION_ALREADY_CREATED,
     SIMCONNECT_EXCEPTION_OBJECT_OUTSIDE_REALITY_BUBBLE,
     SIMCONNECT_EXCEPTION_OBJECT_CONTAINER,
     SIMCONNECT_EXCEPTION_OBJECT_AI,
     SIMCONNECT_EXCEPTION_OBJECT_ATC,
     SIMCONNECT_EXCEPTION_OBJECT_SCHEDULE,
 };
enum SIMCONNECT_FACILITY_LIST_TYPE
Enumerator
SIMCONNECT_FACILITY_LIST_TYPE_AIRPORT
SIMCONNECT_FACILITY_LIST_TYPE_WAYPOINT
SIMCONNECT_FACILITY_LIST_TYPE_NDB
SIMCONNECT_FACILITY_LIST_TYPE_VOR
SIMCONNECT_FACILITY_LIST_TYPE_COUNT
Definition at line 268 of file SimConnect.h.
{
     SIMCONNECT_FACILITY_LIST_TYPE_AIRPORT,
     SIMCONNECT_FACILITY_LIST_TYPE_WAYPOINT,
     SIMCONNECT_FACILITY_LIST_TYPE_NDB,
     SIMCONNECT_FACILITY_LIST_TYPE_VOR,
     SIMCONNECT_FACILITY_LIST_TYPE_COUNT // invalid
 };
enum SIMCONNECT_MISSION_END
Enumerator
SIMCONNECT_MISSION_FAILED
SIMCONNECT_MISSION_CRASHED
SIMCONNECT_MISSION_SUCCEEDED
Definition at line 208 of file SimConnect.h.
{
     SIMCONNECT_MISSION_FAILED,
     SIMCONNECT_MISSION_CRASHED,
     SIMCONNECT_MISSION_SUCCEEDED
 };
enum SIMCONNECT_PERIOD
Enumerator
SIMCONNECT_PERIOD_NEVER
SIMCONNECT_PERIOD_ONCE
SIMCONNECT_PERIOD_VISUAL_FRAME
SIMCONNECT_PERIOD_SIM_FRAME
SIMCONNECT_PERIOD_SECOND
Definition at line 199 of file SimConnect.h.
{
     SIMCONNECT_PERIOD_NEVER,
     SIMCONNECT_PERIOD_ONCE,
     SIMCONNECT_PERIOD_VISUAL_FRAME,
     SIMCONNECT_PERIOD_SIM_FRAME,
     SIMCONNECT_PERIOD_SECOND,
 };
enum SIMCONNECT_RECV_ID
Enumerator
SIMCONNECT_RECV_ID_NULL
SIMCONNECT_RECV_ID_EXCEPTION
SIMCONNECT_RECV_ID_OPEN
SIMCONNECT_RECV_ID_QUIT
SIMCONNECT_RECV_ID_EVENT
SIMCONNECT_RECV_ID_EVENT_OBJECT_ADDREMOVE
SIMCONNECT_RECV_ID_EVENT_FILENAME
SIMCONNECT_RECV_ID_EVENT_FRAME
SIMCONNECT_RECV_ID_SIMOBJECT_DATA
SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE
SIMCONNECT_RECV_ID_WEATHER_OBSERVATION
SIMCONNECT_RECV_ID_CLOUD_STATE
SIMCONNECT_RECV_ID_ASSIGNED_OBJECT_ID
SIMCONNECT_RECV_ID_RESERVED_KEY
SIMCONNECT_RECV_ID_CUSTOM_ACTION
SIMCONNECT_RECV_ID_SYSTEM_STATE
SIMCONNECT_RECV_ID_CLIENT_DATA
SIMCONNECT_RECV_ID_EVENT_WEATHER_MODE
SIMCONNECT_RECV_ID_AIRPORT_LIST
SIMCONNECT_RECV_ID_VOR_LIST
SIMCONNECT_RECV_ID_NDB_LIST
SIMCONNECT_RECV_ID_WAYPOINT_LIST
SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SERVER_STARTED
SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_CLIENT_STARTED
SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SESSION_ENDED
SIMCONNECT_RECV_ID_EVENT_RACE_END
SIMCONNECT_RECV_ID_EVENT_RACE_LAP
Definition at line 82 of file SimConnect.h.
{
     SIMCONNECT_RECV_ID_NULL,
     SIMCONNECT_RECV_ID_EXCEPTION,
     SIMCONNECT_RECV_ID_OPEN,
     SIMCONNECT_RECV_ID_QUIT,
     SIMCONNECT_RECV_ID_EVENT,
     SIMCONNECT_RECV_ID_EVENT_OBJECT_ADDREMOVE,
     SIMCONNECT_RECV_ID_EVENT_FILENAME,
     SIMCONNECT_RECV_ID_EVENT_FRAME,
     SIMCONNECT_RECV_ID_SIMOBJECT_DATA,
     SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE,
     SIMCONNECT_RECV_ID_WEATHER_OBSERVATION,
     SIMCONNECT_RECV_ID_CLOUD_STATE,
     SIMCONNECT_RECV_ID_ASSIGNED_OBJECT_ID,
     SIMCONNECT_RECV_ID_RESERVED_KEY,
     SIMCONNECT_RECV_ID_CUSTOM_ACTION,
     SIMCONNECT_RECV_ID_SYSTEM_STATE,
     SIMCONNECT_RECV_ID_CLIENT_DATA,
     SIMCONNECT_RECV_ID_EVENT_WEATHER_MODE,
     SIMCONNECT_RECV_ID_AIRPORT_LIST,
     SIMCONNECT_RECV_ID_VOR_LIST,
     SIMCONNECT_RECV_ID_NDB_LIST,
     SIMCONNECT_RECV_ID_WAYPOINT_LIST,
     SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SERVER_STARTED,
     SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_CLIENT_STARTED,
     SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SESSION_ENDED,
     SIMCONNECT_RECV_ID_EVENT_RACE_END,
     SIMCONNECT_RECV_ID_EVENT_RACE_LAP,
 };
enum SIMCONNECT_SIMOBJECT_TYPE
Enumerator
SIMCONNECT_SIMOBJECT_TYPE_USER
SIMCONNECT_SIMOBJECT_TYPE_ALL
SIMCONNECT_SIMOBJECT_TYPE_AIRCRAFT
SIMCONNECT_SIMOBJECT_TYPE_HELICOPTER
SIMCONNECT_SIMOBJECT_TYPE_BOAT
SIMCONNECT_SIMOBJECT_TYPE_GROUND
Definition at line 183 of file SimConnect.h.
{
     SIMCONNECT_SIMOBJECT_TYPE_USER,
     SIMCONNECT_SIMOBJECT_TYPE_ALL,
     SIMCONNECT_SIMOBJECT_TYPE_AIRCRAFT,
     SIMCONNECT_SIMOBJECT_TYPE_HELICOPTER,
     SIMCONNECT_SIMOBJECT_TYPE_BOAT,
     SIMCONNECT_SIMOBJECT_TYPE_GROUND,
 };
enum SIMCONNECT_STATE
Enumerator
SIMCONNECT_STATE_OFF
SIMCONNECT_STATE_ON
Definition at line 193 of file SimConnect.h.
                       {
     SIMCONNECT_STATE_OFF,
     SIMCONNECT_STATE_ON,
 };
enum SIMCONNECT_TEXT_RESULT
Enumerator
SIMCONNECT_TEXT_RESULT_MENU_SELECT_1
SIMCONNECT_TEXT_RESULT_MENU_SELECT_2
SIMCONNECT_TEXT_RESULT_MENU_SELECT_3
SIMCONNECT_TEXT_RESULT_MENU_SELECT_4
SIMCONNECT_TEXT_RESULT_MENU_SELECT_5
SIMCONNECT_TEXT_RESULT_MENU_SELECT_6
SIMCONNECT_TEXT_RESULT_MENU_SELECT_7
SIMCONNECT_TEXT_RESULT_MENU_SELECT_8
SIMCONNECT_TEXT_RESULT_MENU_SELECT_9
SIMCONNECT_TEXT_RESULT_MENU_SELECT_10
SIMCONNECT_TEXT_RESULT_DISPLAYED
SIMCONNECT_TEXT_RESULT_QUEUED
SIMCONNECT_TEXT_RESULT_REMOVED
SIMCONNECT_TEXT_RESULT_REPLACED
SIMCONNECT_TEXT_RESULT_TIMEOUT
Definition at line 243 of file SimConnect.h.
{
     SIMCONNECT_TEXT_RESULT_MENU_SELECT_1,
     SIMCONNECT_TEXT_RESULT_MENU_SELECT_2,
     SIMCONNECT_TEXT_RESULT_MENU_SELECT_3,
     SIMCONNECT_TEXT_RESULT_MENU_SELECT_4,
     SIMCONNECT_TEXT_RESULT_MENU_SELECT_5,
     SIMCONNECT_TEXT_RESULT_MENU_SELECT_6,
     SIMCONNECT_TEXT_RESULT_MENU_SELECT_7,
     SIMCONNECT_TEXT_RESULT_MENU_SELECT_8,
     SIMCONNECT_TEXT_RESULT_MENU_SELECT_9,
     SIMCONNECT_TEXT_RESULT_MENU_SELECT_10,
     SIMCONNECT_TEXT_RESULT_DISPLAYED = 0x00010000,
     SIMCONNECT_TEXT_RESULT_QUEUED,
     SIMCONNECT_TEXT_RESULT_REMOVED,
     SIMCONNECT_TEXT_RESULT_REPLACED,
     SIMCONNECT_TEXT_RESULT_TIMEOUT,
 };
enum SIMCONNECT_TEXT_TYPE
Enumerator
SIMCONNECT_TEXT_TYPE_SCROLL_BLACK
SIMCONNECT_TEXT_TYPE_SCROLL_WHITE
SIMCONNECT_TEXT_TYPE_SCROLL_RED
SIMCONNECT_TEXT_TYPE_SCROLL_GREEN
SIMCONNECT_TEXT_TYPE_SCROLL_BLUE
SIMCONNECT_TEXT_TYPE_SCROLL_YELLOW
SIMCONNECT_TEXT_TYPE_SCROLL_MAGENTA
SIMCONNECT_TEXT_TYPE_SCROLL_CYAN
SIMCONNECT_TEXT_TYPE_PRINT_BLACK
SIMCONNECT_TEXT_TYPE_PRINT_WHITE
SIMCONNECT_TEXT_TYPE_PRINT_RED
SIMCONNECT_TEXT_TYPE_PRINT_GREEN
SIMCONNECT_TEXT_TYPE_PRINT_BLUE
SIMCONNECT_TEXT_TYPE_PRINT_YELLOW
SIMCONNECT_TEXT_TYPE_PRINT_MAGENTA
SIMCONNECT_TEXT_TYPE_PRINT_CYAN
SIMCONNECT_TEXT_TYPE_MENU
Definition at line 223 of file SimConnect.h.
{
     SIMCONNECT_TEXT_TYPE_SCROLL_BLACK,
     SIMCONNECT_TEXT_TYPE_SCROLL_WHITE,
     SIMCONNECT_TEXT_TYPE_SCROLL_RED,
     SIMCONNECT_TEXT_TYPE_SCROLL_GREEN,
     SIMCONNECT_TEXT_TYPE_SCROLL_BLUE,
     SIMCONNECT_TEXT_TYPE_SCROLL_YELLOW,
     SIMCONNECT_TEXT_TYPE_SCROLL_MAGENTA,
     SIMCONNECT_TEXT_TYPE_SCROLL_CYAN,
     SIMCONNECT_TEXT_TYPE_PRINT_BLACK=0x0100,
     SIMCONNECT_TEXT_TYPE_PRINT_WHITE,
     SIMCONNECT_TEXT_TYPE_PRINT_RED,
     SIMCONNECT_TEXT_TYPE_PRINT_GREEN,
     SIMCONNECT_TEXT_TYPE_PRINT_BLUE,
     SIMCONNECT_TEXT_TYPE_PRINT_YELLOW,
     SIMCONNECT_TEXT_TYPE_PRINT_MAGENTA,
     SIMCONNECT_TEXT_TYPE_PRINT_CYAN,
     SIMCONNECT_TEXT_TYPE_MENU=0x0200,
 };
enum SIMCONNECT_WEATHER_MODE
Enumerator
SIMCONNECT_WEATHER_MODE_THEME
SIMCONNECT_WEATHER_MODE_RWW
SIMCONNECT_WEATHER_MODE_CUSTOM
SIMCONNECT_WEATHER_MODE_GLOBAL
Definition at line 261 of file SimConnect.h.
{
     SIMCONNECT_WEATHER_MODE_THEME,
     SIMCONNECT_WEATHER_MODE_RWW,
     SIMCONNECT_WEATHER_MODE_CUSTOM,
     SIMCONNECT_WEATHER_MODE_GLOBAL,
 };
Function Documentation
SIMCONNECTAPI SimConnect_AddClientEventToNotificationGroup (HANDLE hSimConnect, SIMCONNECT_NOTIFICATION_GROUP_ID GroupID, SIMCONNECT_CLIENT_EVENT_ID EventID, BOOL bMaskable = FALSE)
Referenced by DLLStart(), and testCockpitCamera().
SIMCONNECTAPI SimConnect_AddToClientDataDefinition (HANDLE hSimConnect, SIMCONNECT_CLIENT_DATA_DEFINITION_ID DefineID, DWORD dwOffset, DWORD dwSizeOrType, float fEpsilon = 0, DWORD DatumID = SIMCONNECT_UNUSED)
SIMCONNECTAPI SimConnect_AddToDataDefinition (HANDLE hSimConnect, SIMCONNECT_DATA_DEFINITION_ID DefineID, const char * DatumName, const char * UnitsName, SIMCONNECT_DATATYPE DatumType = SIMCONNECT_DATATYPE_FLOAT64, float fEpsilon = 0, DWORD DatumID = SIMCONNECT_UNUSED)
Referenced by Request::addToDataDef(), safe::SimReceiver::addToDataDefinition(), and safe::DataSender::DataSender().
SIMCONNECTAPI SimConnect_AICreateEnrouteATCAircraft (HANDLE hSimConnect, const char * szContainerTitle, const char * szTailNumber, int iFlightNumber, const char * szFlightPlanPath, double dFlightPlanPosition, BOOL bTouchAndGo, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_AICreateNonATCAircraft (HANDLE hSimConnect, const char * szContainerTitle, const char * szTailNumber, SIMCONNECT_DATA_INITPOSITION InitPos, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_AICreateParkedATCAircraft (HANDLE hSimConnect, const char * szContainerTitle, const char * szTailNumber, const char * szAirportID, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_AICreateSimulatedObject (HANDLE hSimConnect, const char * szContainerTitle, SIMCONNECT_DATA_INITPOSITION InitPos, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_AIReleaseControl (HANDLE hSimConnect, SIMCONNECT_OBJECT_ID ObjectID, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_AIRemoveObject (HANDLE hSimConnect, SIMCONNECT_OBJECT_ID ObjectID, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_AISetAircraftFlightPlan (HANDLE hSimConnect, SIMCONNECT_OBJECT_ID ObjectID, const char * szFlightPlanPath, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_CallDispatch (HANDLE hSimConnect, DispatchProc pfcnDispatch, void * pContext)
Referenced by SimConnection::dispatch(), DLLStart(), and testCockpitCamera().
SIMCONNECTAPI SimConnect_CameraSetRelative6DOF (HANDLE hSimConnect, float fDeltaX, float fDeltaY, float fDeltaZ, float fPitchDeg, float fBankDeg, float fHeadingDeg)
Referenced by MyDispatchProcCC(), and MyDispatchProcDLL().
SIMCONNECTAPI SimConnect_ClearClientDataDefinition (HANDLE hSimConnect, SIMCONNECT_CLIENT_DATA_DEFINITION_ID DefineID)
SIMCONNECTAPI SimConnect_ClearDataDefinition (HANDLE hSimConnect, SIMCONNECT_DATA_DEFINITION_ID DefineID)
SIMCONNECTAPI SimConnect_ClearInputGroup (HANDLE hSimConnect, SIMCONNECT_INPUT_GROUP_ID GroupID)
SIMCONNECTAPI SimConnect_ClearNotificationGroup (HANDLE hSimConnect, SIMCONNECT_NOTIFICATION_GROUP_ID GroupID)
SIMCONNECTAPI SimConnect_Close (HANDLE hSimConnect)
Referenced by safe::SimReceiver::close(), DLLStop(), and testCockpitCamera().
SIMCONNECTAPI SimConnect_CompleteCustomMissionAction (HANDLE hSimConnect, const GUID guidInstanceId)
SIMCONNECTAPI SimConnect_CreateClientData (HANDLE hSimConnect, SIMCONNECT_CLIENT_DATA_ID ClientDataID, DWORD dwSize, SIMCONNECT_CREATE_CLIENT_DATA_FLAG Flags)
SIMCONNECTAPI SimConnect_ExecuteMissionAction (HANDLE hSimConnect, const GUID guidInstanceId)
SIMCONNECTAPI SimConnect_FlightLoad (HANDLE hSimConnect, const char * szFileName)
SIMCONNECTAPI SimConnect_FlightPlanLoad (HANDLE hSimConnect, const char * szFileName)
SIMCONNECTAPI SimConnect_FlightSave (HANDLE hSimConnect, const char * szFileName, const char * szTitle, const char * szDescription, DWORD Flags)
SIMCONNECTAPI SimConnect_GetLastSentPacketID (HANDLE hSimConnect, DWORD * pdwError)
Referenced by SimExManager::addSendRecord(), SimExManager::firstSendRecord(), and SimExManager::lastSendRecord().
SIMCONNECTAPI SimConnect_GetNextDispatch (HANDLE hSimConnect, SIMCONNECT_RECV ** ppData, DWORD * pcbData)
SIMCONNECTAPI SimConnect_InsertString (char * pDest, DWORD cbDest, void ** ppEnd, DWORD * pcbStringV, const char * pSource)
SIMCONNECTAPI SimConnect_MapClientDataNameToID (HANDLE hSimConnect, const char * szClientDataName, SIMCONNECT_CLIENT_DATA_ID ClientDataID)
SIMCONNECTAPI SimConnect_MapClientEventToSimEvent (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID EventID, const char * EventName = "")
Referenced by DLLStart(), safe::DataSender::freeze(), and testCockpitCamera().
SIMCONNECTAPI SimConnect_MapInputEventToClientEvent (HANDLE hSimConnect, SIMCONNECT_INPUT_GROUP_ID GroupID, const char * szInputDefinition, SIMCONNECT_CLIENT_EVENT_ID DownEventID, DWORD DownValue = 0, SIMCONNECT_CLIENT_EVENT_ID UpEventID = (SIMCONNECT_CLIENT_EVENT_ID) SIMCONNECT_UNUSED, DWORD UpValue = 0, BOOL bMaskable = FALSE)
Referenced by DLLStart(), and testCockpitCamera().
SIMCONNECTAPI SimConnect_MenuAddItem (HANDLE hSimConnect, const char * szMenuItem, SIMCONNECT_CLIENT_EVENT_ID MenuEventID, DWORD dwData)
Referenced by DLLStart().
SIMCONNECTAPI SimConnect_MenuAddSubItem (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID MenuEventID, const char * szMenuItem, SIMCONNECT_CLIENT_EVENT_ID SubMenuEventID, DWORD dwData)
Referenced by DLLStart().
SIMCONNECTAPI SimConnect_MenuDeleteItem (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID MenuEventID)
SIMCONNECTAPI SimConnect_MenuDeleteSubItem (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID MenuEventID, const SIMCONNECT_CLIENT_EVENT_ID SubMenuEventID)
SIMCONNECTAPI SimConnect_Open (HANDLE * phSimConnect, LPCSTR szName, HWND hWnd, DWORD UserEventWin32, HANDLE hEventHandle, DWORD ConfigIndex)
Referenced by safe::DataSender::DataSender(), DLLStart(), safe::SimReceiver::SimReceiver(), and testCockpitCamera().
SIMCONNECTAPI SimConnect_RemoveClientEvent (HANDLE hSimConnect, SIMCONNECT_NOTIFICATION_GROUP_ID GroupID, SIMCONNECT_CLIENT_EVENT_ID EventID)
SIMCONNECTAPI SimConnect_RemoveInputEvent (HANDLE hSimConnect, SIMCONNECT_INPUT_GROUP_ID GroupID, const char * szInputDefinition)
SIMCONNECTAPI SimConnect_RequestClientData (HANDLE hSimConnect, SIMCONNECT_CLIENT_DATA_ID ClientDataID, SIMCONNECT_DATA_REQUEST_ID RequestID, SIMCONNECT_CLIENT_DATA_DEFINITION_ID DefineID, SIMCONNECT_CLIENT_DATA_PERIOD Period = SIMCONNECT_CLIENT_DATA_PERIOD_ONCE, SIMCONNECT_CLIENT_DATA_REQUEST_FLAG Flags = 0, DWORD origin = 0, DWORD interval = 0, DWORD limit = 0)
SIMCONNECTAPI SimConnect_RequestDataOnSimObject (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, SIMCONNECT_DATA_DEFINITION_ID DefineID, SIMCONNECT_OBJECT_ID ObjectID, SIMCONNECT_PERIOD Period, SIMCONNECT_DATA_REQUEST_FLAG Flags = 0, DWORD origin = 0, DWORD interval = 0, DWORD limit = 0)
Referenced by safe::SimReceiver::onRecvEvent().
SIMCONNECTAPI SimConnect_RequestDataOnSimObjectType (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, SIMCONNECT_DATA_DEFINITION_ID DefineID, DWORD dwRadiusMeters, SIMCONNECT_SIMOBJECT_TYPE type)
SIMCONNECTAPI SimConnect_RequestFacilitiesList (HANDLE hSimConnect, SIMCONNECT_FACILITY_LIST_TYPE type, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_RequestNotificationGroup (HANDLE hSimConnect, SIMCONNECT_NOTIFICATION_GROUP_ID GroupID, DWORD dwReserved = 0, DWORD Flags = 0)
SIMCONNECTAPI SimConnect_RequestReservedKey (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID EventID, const char * szKeyChoice1 = "", const char * szKeyChoice2 = "", const char * szKeyChoice3 = "")
SIMCONNECTAPI SimConnect_RequestResponseTimes (HANDLE hSimConnect, DWORD nCount, float * fElapsedSeconds)
SIMCONNECTAPI SimConnect_RequestSystemState (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, const char * szState)
SIMCONNECTAPI SimConnect_RetrieveString (SIMCONNECT_RECV * pData, DWORD cbData, void * pStringV, char ** pszString, DWORD * pcbString)
SIMCONNECTAPI SimConnect_SetClientData (HANDLE hSimConnect, SIMCONNECT_CLIENT_DATA_ID ClientDataID, SIMCONNECT_CLIENT_DATA_DEFINITION_ID DefineID, SIMCONNECT_CLIENT_DATA_SET_FLAG Flags, DWORD dwReserved, DWORD cbUnitSize, void * pDataSet)
SIMCONNECTAPI SimConnect_SetDataOnSimObject (HANDLE hSimConnect, SIMCONNECT_DATA_DEFINITION_ID DefineID, SIMCONNECT_OBJECT_ID ObjectID, SIMCONNECT_DATA_SET_FLAG Flags, DWORD ArrayCount, DWORD cbUnitSize, void * pDataSet)
Referenced by safe::DataSender::sendLatLonAlt(), safe::DataSender::sendPBH(), and safe::DataSender::sendPos().
SIMCONNECTAPI SimConnect_SetInputGroupPriority (HANDLE hSimConnect, SIMCONNECT_INPUT_GROUP_ID GroupID, DWORD uPriority)
SIMCONNECTAPI SimConnect_SetInputGroupState (HANDLE hSimConnect, SIMCONNECT_INPUT_GROUP_ID GroupID, DWORD dwState)
Referenced by DLLStart(), and testCockpitCamera().
SIMCONNECTAPI SimConnect_SetNotificationGroupPriority (HANDLE hSimConnect, SIMCONNECT_NOTIFICATION_GROUP_ID GroupID, DWORD uPriority)
Referenced by DLLStart(), and testCockpitCamera().
SIMCONNECTAPI SimConnect_SetSystemEventState (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID EventID, SIMCONNECT_STATE dwState)
SIMCONNECTAPI SimConnect_SetSystemState (HANDLE hSimConnect, const char * szState, DWORD dwInteger, float fFloat, const char * szString)
SIMCONNECTAPI SimConnect_SubscribeToFacilities (HANDLE hSimConnect, SIMCONNECT_FACILITY_LIST_TYPE type, SIMCONNECT_DATA_REQUEST_ID RequestID)
SIMCONNECTAPI SimConnect_SubscribeToSystemEvent (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID EventID, const char * SystemEventName)
Referenced by safe::SimReceiver::SimReceiver().
SIMCONNECTAPI SimConnect_Text (HANDLE hSimConnect, SIMCONNECT_TEXT_TYPE type, float fTimeSeconds, SIMCONNECT_CLIENT_EVENT_ID EventID, DWORD cbUnitSize, void * pDataSet)
SIMCONNECTAPI SimConnect_TransmitClientEvent (HANDLE hSimConnect, SIMCONNECT_OBJECT_ID ObjectID, SIMCONNECT_CLIENT_EVENT_ID EventID, DWORD dwData, SIMCONNECT_NOTIFICATION_GROUP_ID GroupID, SIMCONNECT_EVENT_FLAG Flags)
Referenced by safe::DataSender::freeze().
SIMCONNECTAPI SimConnect_UnsubscribeFromSystemEvent (HANDLE hSimConnect, SIMCONNECT_CLIENT_EVENT_ID EventID)
SIMCONNECTAPI SimConnect_UnsubscribeToFacilities (HANDLE hSimConnect, SIMCONNECT_FACILITY_LIST_TYPE type)
SIMCONNECTAPI SimConnect_WeatherCreateStation (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, const char * szICAO, const char * szName, float lat, float lon, float alt)
SIMCONNECTAPI SimConnect_WeatherCreateThermal (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, float lat, float lon, float alt, float radius, float height, float coreRate = 3.0f, float coreTurbulence = 0.05f, float sinkRate = 3.0f, float sinkTurbulence = 0.2f, float coreSize = 0.4f, float coreTransitionSize = 0.1f, float sinkLayerSize = 0.4f, float sinkTransitionSize = 0.1f)
SIMCONNECTAPI SimConnect_WeatherRemoveStation (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, const char * szICAO)
SIMCONNECTAPI SimConnect_WeatherRemoveThermal (HANDLE hSimConnect, SIMCONNECT_OBJECT_ID ObjectID)
SIMCONNECTAPI SimConnect_WeatherRequestCloudState (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, float minLat, float minLon, float minAlt, float maxLat, float maxLon, float maxAlt, DWORD dwFlags = 0)
SIMCONNECTAPI SimConnect_WeatherRequestInterpolatedObservation (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, float lat, float lon, float alt)
SIMCONNECTAPI SimConnect_WeatherRequestObservationAtNearestStation (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, float lat, float lon)
SIMCONNECTAPI SimConnect_WeatherRequestObservationAtStation (HANDLE hSimConnect, SIMCONNECT_DATA_REQUEST_ID RequestID, const char * szICAO)
SIMCONNECTAPI SimConnect_WeatherSetDynamicUpdateRate (HANDLE hSimConnect, DWORD dwRate)
SIMCONNECTAPI SimConnect_WeatherSetModeCustom (HANDLE hSimConnect)
SIMCONNECTAPI SimConnect_WeatherSetModeGlobal (HANDLE hSimConnect)
SIMCONNECTAPI SimConnect_WeatherSetModeServer (HANDLE hSimConnect, DWORD dwPort, DWORD dwSeconds)
SIMCONNECTAPI SimConnect_WeatherSetModeTheme (HANDLE hSimConnect, const char * szThemeName)
SIMCONNECTAPI SimConnect_WeatherSetObservation (HANDLE hSimConnect, DWORD Seconds, const char * szMETAR)
Variable Documentation
const DWORD INITPOSITION_AIRSPEED_CRUISE = -1 static
Definition at line 60 of file SimConnect.h.
const DWORD INITPOSITION_AIRSPEED_KEEP = -2 static
Definition at line 61 of file SimConnect.h.
const DWORD MAX_METAR_LENGTH = 2000 static
Definition at line 53 of file SimConnect.h.
const float MAX_THERMAL_RATE = 1000 static
Definition at line 57 of file SimConnect.h.
const float MAX_THERMAL_SIZE = 100000 static
Definition at line 56 of file SimConnect.h.
const float SIMCONNECT_CAMERA_IGNORE_FIELD = FLT_MAX static
Definition at line 40 of file SimConnect.h.
Referenced by MyDispatchProcCC(), and MyDispatchProcDLL().
const DWORD SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_CHANGED = 0x00000001 static
Definition at line 328 of file SimConnect.h.
const DWORD SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_DEFAULT = 0x00000000 static
Definition at line 327 of file SimConnect.h.
const DWORD SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_TAGGED = 0x00000002 static
Definition at line 329 of file SimConnect.h.
const DWORD SIMCONNECT_CLIENT_DATA_SET_FLAG_DEFAULT = 0x00000000 static
Definition at line 334 of file SimConnect.h.
const DWORD SIMCONNECT_CLIENT_DATA_SET_FLAG_TAGGED = 0x00000001 static
Definition at line 335 of file SimConnect.h.
const DWORD SIMCONNECT_CLIENTDATA_MAX_SIZE = 8192 static
Definition at line 42 of file SimConnect.h.
const DWORD SIMCONNECT_CLIENTDATAOFFSET_AUTO = -1 static
Definition at line 72 of file SimConnect.h.
const DWORD SIMCONNECT_CLIENTDATATYPE_FLOAT32 = -5 static
Definition at line 68 of file SimConnect.h.
const DWORD SIMCONNECT_CLIENTDATATYPE_FLOAT64 = -6 static
Definition at line 69 of file SimConnect.h.
const DWORD SIMCONNECT_CLIENTDATATYPE_INT16 = -2 static
Definition at line 65 of file SimConnect.h.
const DWORD SIMCONNECT_CLIENTDATATYPE_INT32 = -3 static
Definition at line 66 of file SimConnect.h.
const DWORD SIMCONNECT_CLIENTDATATYPE_INT64 = -4 static
Definition at line 67 of file SimConnect.h.
const DWORD SIMCONNECT_CLIENTDATATYPE_INT8 = -1 static
Definition at line 64 of file SimConnect.h.
const int SIMCONNECT_CLOUD_STATE_ARRAY_SIZE = SIMCONNECT_CLOUD_STATE_ARRAY_WIDTH*SIMCONNECT_CLOUD_STATE_ARRAY_WIDTH static
Definition at line 500 of file SimConnect.h.
const int SIMCONNECT_CLOUD_STATE_ARRAY_WIDTH = 64 static
Definition at line 499 of file SimConnect.h.
const DWORD SIMCONNECT_CREATE_CLIENT_DATA_FLAG_DEFAULT = 0x00000000 static
Definition at line 321 of file SimConnect.h.
const DWORD SIMCONNECT_CREATE_CLIENT_DATA_FLAG_READ_ONLY = 0x00000001 static
Definition at line 322 of file SimConnect.h.
const DWORD SIMCONNECT_DATA_REQUEST_FLAG_CHANGED = 0x00000001 static
Definition at line 309 of file SimConnect.h.
Referenced by safe::SimReceiver::onRecvEvent().
const DWORD SIMCONNECT_DATA_REQUEST_FLAG_DEFAULT = 0x00000000 static
Definition at line 308 of file SimConnect.h.
const DWORD SIMCONNECT_DATA_REQUEST_FLAG_TAGGED = 0x00000002 static
Definition at line 310 of file SimConnect.h.
const DWORD SIMCONNECT_DATA_SET_FLAG_DEFAULT = 0x00000000 static
Definition at line 315 of file SimConnect.h.
const DWORD SIMCONNECT_DATA_SET_FLAG_TAGGED = 0x00000001 static
Definition at line 316 of file SimConnect.h.
const DWORD SIMCONNECT_EVENT_FLAG_DEFAULT = 0x00000000 static
Definition at line 300 of file SimConnect.h.
const DWORD SIMCONNECT_EVENT_FLAG_FAST_REPEAT_TIMER = 0x00000001 static
Definition at line 301 of file SimConnect.h.
const DWORD SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY = 0x00000010 static
Definition at line 303 of file SimConnect.h.
Referenced by safe::DataSender::freeze().
const DWORD SIMCONNECT_EVENT_FLAG_SLOW_REPEAT_TIMER = 0x00000002 static
Definition at line 302 of file SimConnect.h.
const DWORD SIMCONNECT_GROUP_PRIORITY_DEFAULT = 2000000000 static
Definition at line 49 of file SimConnect.h.
const DWORD SIMCONNECT_GROUP_PRIORITY_HIGHEST = 1 static
Definition at line 46 of file SimConnect.h.
Referenced by DLLStart(), safe::DataSender::freeze(), and testCockpitCamera().
const DWORD SIMCONNECT_GROUP_PRIORITY_HIGHEST_MASKABLE = 10000000 static
Definition at line 47 of file SimConnect.h.
const DWORD SIMCONNECT_GROUP_PRIORITY_LOWEST = 4000000000 static
Definition at line 50 of file SimConnect.h.
const DWORD SIMCONNECT_GROUP_PRIORITY_STANDARD = 1900000000 static
Definition at line 48 of file SimConnect.h.
const DWORD SIMCONNECT_OBJECT_ID_USER = 0 static
Definition at line 38 of file SimConnect.h.
Referenced by safe::DataSender::freeze(), safe::SimReceiver::onRecvEvent(), safe::DataSender::sendLatLonAlt(), safe::DataSender::sendPBH(), and safe::DataSender::sendPos().
const DWORD SIMCONNECT_OPEN_CONFIGINDEX_LOCAL = -1 static
Definition at line 75 of file SimConnect.h.
const DWORD SIMCONNECT_RECV_ID_VOR_LIST_HAS_DME = 0x00000008 static
Definition at line 281 of file SimConnect.h.
const DWORD SIMCONNECT_RECV_ID_VOR_LIST_HAS_GLIDE_SLOPE = 0x00000004 static
Definition at line 280 of file SimConnect.h.
const DWORD SIMCONNECT_RECV_ID_VOR_LIST_HAS_LOCALIZER = 0x00000002 static
Definition at line 279 of file SimConnect.h.
const DWORD SIMCONNECT_RECV_ID_VOR_LIST_HAS_NAV_SIGNAL = 0x00000001 static
Definition at line 278 of file SimConnect.h.
const DWORD SIMCONNECT_SOUND_SYSTEM_EVENT_DATA_MASTER = 0x00000001 static
Definition at line 347 of file SimConnect.h.
const DWORD SIMCONNECT_UNUSED = DWORD_MAX static
Definition at line 37 of file SimConnect.h.
const DWORD SIMCONNECT_VIEW_SYSTEM_EVENT_DATA_COCKPIT_2D = 0x00000001 static
Definition at line 340 of file SimConnect.h.
const DWORD SIMCONNECT_VIEW_SYSTEM_EVENT_DATA_COCKPIT_VIRTUAL = 0x00000002 static
Definition at line 341 of file SimConnect.h.
const DWORD SIMCONNECT_VIEW_SYSTEM_EVENT_DATA_ORTHOGONAL = 0x00000004 static
Definition at line 342 of file SimConnect.h.
const DWORD SIMCONNECT_WAYPOINT_ALTITUDE_IS_AGL = 0x20 static
Definition at line 292 of file SimConnect.h.
const DWORD SIMCONNECT_WAYPOINT_COMPUTE_VERTICAL_SPEED = 0x10 static
Definition at line 291 of file SimConnect.h.
const DWORD SIMCONNECT_WAYPOINT_NONE = 0x00 static
Definition at line 288 of file SimConnect.h.
const DWORD SIMCONNECT_WAYPOINT_ON_GROUND = 0x00100000 static
Definition at line 293 of file SimConnect.h.
const DWORD SIMCONNECT_WAYPOINT_REVERSE = 0x00200000 static
Definition at line 294 of file SimConnect.h.
const DWORD SIMCONNECT_WAYPOINT_SPEED_REQUESTED = 0x04 static
Definition at line 289 of file SimConnect.h.
const DWORD SIMCONNECT_WAYPOINT_THROTTLE_REQUESTED = 0x08 static
Definition at line 290 of file SimConnect.h.
const DWORD SIMCONNECT_WAYPOINT_WRAP_TO_FIRST = 0x00400000 static
Definition at line 295 of file SimConnect.h.