StartAir_Safe: face Struct Reference
face Struct Reference
#include <objloader.h>
Public Member Functions
face (int facen, int f1, int f2, int f3, int t1, int t2, int t3, int m)
face (int facen, int f1, int f2, int f3, int f4, int t1, int t2, int t3, int t4, int m)
Public Attributes
int facenum
bool four
int faces [4]
int texcoord [4]
int mat
Detailed Description
Definition at line 27 of file objloader.h.
Constructor & Destructor Documentation
face::face (int facen, int f1, int f2, int f3, int t1, int t2, int t3, int m)
Definition at line 15 of file objloader.cpp.
References f1(), f2(), facenum, faces, four, and mat.
{
         facenum = facen;
         faces[0] = f1;
         faces[1] = f2;
         faces[2] = f3;
         texcoord[0] = t1;
         texcoord[1] = t2;
         texcoord[2] = t3;
         mat = m;
         four = false;
 }
face::face (int facen, int f1, int f2, int f3, int f4, int t1, int t2, int t3, int t4, int m)
Definition at line 27 of file objloader.cpp.
References f1(), f2(), facenum, faces, four, and mat.
{
         facenum = facen;
         faces[0] = f1;
         faces[1] = f2;
         faces[2] = f3;
         faces[3] = f4;
         texcoord[0] = t1;
         texcoord[1] = t2;
         texcoord[2] = t3;
         texcoord[3] = t4;
         mat = m;
         four = true;
 }
Member Data Documentation
int face::facenum
Definition at line 28 of file objloader.h.
Referenced by face().
int face::faces[4]
Definition at line 30 of file objloader.h.
Referenced by face().
bool face::four
Definition at line 29 of file objloader.h.
Referenced by face().
int face::mat
Definition at line 32 of file objloader.h.
Referenced by face().
int face::texcoord[4]
Definition at line 31 of file objloader.h.
The documentation for this struct was generated from the following files:
TestOpenGl/TestOpenGl/objloader.h
TestOpenGl/TestOpenGl/objloader.cpp