StartAir_Safe: TestOpenGl/TestOpenGl/main.cpp File Reference
main.cpp File Reference
#include "objloader.h"
Functions
void init ()
void display ()
int main (int argc, char **argv)
Variables
float angle = 0.0
int cube
objloader obj
Function Documentation
void display ()
Definition at line 27 of file main.cpp.
References cube.
Referenced by main().
 {
         glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
         glLoadIdentity();
         float pos[] = { -1.0, 1.0, -2.0, 1.0 };
         glLightfv(GL_LIGHT0, GL_POSITION, pos);
         glTranslatef(0.0, -30.0, -100.0);
         glCallList(cube);       //and display it
 }
void init ()
Definition at line 12 of file main.cpp.
References cube, and objloader::load().
Referenced by main().
 {
         glClearColor(0.5, 0.5, 0.5, 1.0);
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluPerspective(45, 640.0 / 480.0, 1.0, 500.0);
         glMatrixMode(GL_MODELVIEW);
         glEnable(GL_DEPTH_TEST);
         cube = obj.load("test.obj");      //load it
         glEnable(GL_LIGHTING);
         glEnable(GL_LIGHT0);
         float col[] = { 1.0, 1.0, 1.0, 1.0 };
         glLightfv(GL_LIGHT0, GL_DIFFUSE, col);
 }
int main (int argc, char ** argv)
Definition at line 38 of file main.cpp.
References angle, display(), and init().
 {
         SDL_Init(SDL_INIT_EVERYTHING);
         SDL_Surface* screen = SDL_SetVideoMode(640, 480, 32, SDL_SWSURFACE | SDL_OPENGL);
         bool running = true;
         Uint32 start;
         SDL_Event event;
         init();
         while (running)
         {
                 start = SDL_GetTicks();
                 while (SDL_PollEvent(&event))
                 {
                         switch (event.type)
{
                                 case SDL_QUIT:
                                         running = false;
                                         break;
                         }
                 }
                 display();
                 SDL_GL_SwapBuffers();
                 angle += 0.5;
                 if (angle>360)
                         angle -= 360;
                 if (1000 / 30>(SDL_GetTicks() - start))
                         SDL_Delay(1000 / 30 - (SDL_GetTicks() - start));
         }
         SDL_Quit();
         return 0;
 }
Variable Documentation
float angle = 0.0
Definition at line 8 of file main.cpp.
Referenced by main().
int cube
Definition at line 10 of file main.cpp.
Referenced by display(), and init().
objloader obj
Definition at line 11 of file main.cpp.